### PR TITLE
`check_release_hash` improvements

### LINKED ISSUE #3651: stellar/horizon: check_release_binaries could be improved somewhat
### What problem does your feature solve?

- Right now you can't use the check_release_binaries against a deb package unless it is in the stable track.
- The output is very unintuitive as to whether it passed or failed.

### What would you like to see?

- The check_release_binaries dockerfile to include unstable, so we can check that before promoting to master.
- Make the output more obvious whether it failed or not

### PR DESCRIPTION
**Pull request by bartekn**
Several `check_release_hash` script improvements:
* Run `apt-get` commands separately. Commands were previously joined by `&&` operator which returned 0 code in case any of the commands failure (🤔).
* Hide hashes if they match.
* Add unstable repo.

Close #3651.

### CODE REVIEW

File: services/horizon/internal/scripts/check_release_hash/check.sh [hunk 1]
```diff
@@ -23,30 +25,57 @@ git checkout $TAG
...
+            msg="$TAG-$S NO MATCH! github=$released compile=$dist"
+        fi
     fi
-done
 
-echo "debian package"
-shasum -a 256 $(which stellar-horizon)
\ No newline at end of file
+    echo $msg
+done
```
Comment (tamirms) [inline services/horizon/internal/scripts/check_release_hash/check.sh:81]: will it exit with a non zero status if there is a mismatch?

Comment (bartekn) [reply services/horizon/internal/scripts/check_release_hash/check.sh:81]: No, but it didn't before this update too. I'm not sure it's required, the image probably won't be used in any automated process.

**Review by tamirms — APPROVED** [review]
