### PR TITLE
Fix LoadAccountMerge so that it returns horizon errors #529

### LINKED ISSUE #529: LoadAccountMergeAmount does not check for horizon error
[`Client.LoadAccountMergeAmount`](https://github.com/stellar/go/blob/master/clients/horizon/client.go#L269) makes a request to horizon but does not check for an error. As a result if there is a horizon error it will likely always return this error, instead of the horizon error.
```
Could not find `account_credited` effect in `account_merge` operation effects`.
```

It should probably use something like [decodeResponse](https://github.com/stellar/go/blob/4c8cfd0/clients/horizon/internal.go#L16) to unmarshal the horizon response. Although I don't understand why that method accepts http status [200, 300) instead of just 200.

Here is a hacked up [standalone example](https://play.golang.org/p/h3avUsBe33C) of the gist of this bug.

### PR DESCRIPTION
**Pull request by robertDurst**
Closes #529

### CODE REVIEW

File: clients/horizon/responses.go [hunk 1]
```diff
@@ -146,6 +147,13 @@ type Payment struct {
 	}
 }
 
+// PaymentsPage contains page of effects returned by Horizon.
+type PaymentsPage struct {
+	Embedded struct {
+		Records []Payment
+	} `json:"_embedded"`
+}
```
Comment (bartekn) [inline clients/horizon/responses.go]: It seems that this struct is only used in tests. Can we maybe remove it until we have `LoadPayments` method? In tests we can use a single payment.

Comment (robertDurst) [reply clients/horizon/responses.go]: Good point.
