### PR TITLE
services/horizon: Fix captive core tests to write to /tmp, instead of polluting the repo

### LINKED ISSUE #4290: ingest/ledgerbackend: change captive-core unit tests to use storage path in /tmp
### What version are you using?

2.15.1

### What did you do?

`go test ./ingest/ledgerbackend/...`

### What did you expect to see?
no temporary test files generated during test execution in checked out repo paths

### What did you see instead?
several `./ingest/ledgerbackend/captive-core-xyz/` sub-folders were created in current checked out working directory

### PR DESCRIPTION
**Pull request by paulbellamy**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Write captive core test files to `/tmp`. So they don't pollute local workspace.

### Why

Fixes #4290

### CODE REVIEW

File: ingest/ledgerbackend/captive_core_backend_test.go [hunk 1]
```diff
@@ -131,6 +133,9 @@ type testLedgerHeader struct {
 }
 
 func TestCaptiveNew(t *testing.T) {
+	storagePath, err := os.MkdirTemp(os.TempDir(), "captive-core-*")
+	require.NoError(t, err)
```
Comment (leighmcculloch) [inline ingest/ledgerbackend/captive_core_backend_test.go:137]: Could you add a defer to remove the directory after the test finishes? Or first that compromise the ability to debug failing tests?

File: ingest/ledgerbackend/captive_core_backend_test.go [hunk 2]
```diff
@@ -131,6 +133,9 @@ type testLedgerHeader struct {
 }
 
 func TestCaptiveNew(t *testing.T) {
+	storagePath, err := os.MkdirTemp(os.TempDir(), "captive-core-*")
```
Comment (leighmcculloch) [inline ingest/ledgerbackend/captive_core_backend_test.go:136]: Fyi if you use the empty steering it will use the temp for by default. The first param is optional.
```suggestion
	storagePath, err := os.MkdirTemp("", "captive-core-*")
```

**Review by leighmcculloch — APPROVED** [review]
Two requests above, but regardless this is 🎉.
