### PR TITLE
Fix SEP 10 validation tests

### LINKED ISSUE #1589: Intermittent error in TestVerifyChallengeTxSigned on CircleCI
I ran into an unexpected error in TestVerifyChallengeTxSigned test during this CircleCI run:
https://circleci.com/gh/stellar/go/5451?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

--- FAIL: TestVerifyChallengeTxSigned (0.02s)
	Error Trace:	transaction_test.go:1329
	Error:		Received unexpected error:
			transaction is not within range of the specified timebounds
			github.com/stellar/go/support/errors.New
				/go/src/github.com/stellar/go/support/errors/main.go:36
			github.com/stellar/go/txnbuild.VerifyChallengeTx
				/go/src/github.com/stellar/go/txnbuild/transaction.go:444
			github.com/stellar/go/txnbuild.TestVerifyChallengeTxSigned
				/go/src/github.com/stellar/go/txnbuild/transaction_test.go:1328
			testing.tRunner
				/usr/local/go/src/testing/testing.go:777
			runtime.goexit
				/usr/local/go/src/runtime/asm_amd64.s:2361
		

	Error Trace:	transaction_test.go:1330
	Error:		Not equal: 
			expected: true
			received: false
	Messages:	challenge should be valid

### PR DESCRIPTION
**Pull request by ire-and-curses**
Fixes #1589 by updating tests to use seconds, not nanoseconds. Added validation check to prevent accidentally passing tiny durations, and updated docstring.

### CODE REVIEW

File: txnbuild/transaction.go [hunk 1]
```diff
@@ -441,7 +443,8 @@ func VerifyChallengeTx(challengeTx, serverAccountID, network string) (bool, erro
 	}
 	currentTime := time.Now().UTC().Unix()
 	if currentTime < tx.Timebounds.MinTime || currentTime > tx.Timebounds.MaxTime {
-		return false, errors.New("transaction is not within range of the specified timebounds")
+		return false, errors.New(fmt.Sprintf("transaction is not within range of the specified timebounds (currentTime=%d, MinTime=%d, MaxTime=%d)",
```
Comment (poliha) [inline txnbuild/transaction.go]: We can use `errors.Errorf()` here
