### PR TITLE
exp/ingest/ledgerbackend: Handle Stellar-Core process exit gracefully

### LINKED ISSUE #2705: Handle Stellar-Core errors and exits gracefully
`CaptiveStellarCore` does not handle Stellar-Core errors and exits gracefully:
* When Stellar-Core exits with non-zero exit code the next request to `CaptiveStellarCore` should fail with the error and users should be able to restart the process using `PrepareRange`.
* When Stellar-Core exits without an error make sure the code is able to restart the process if needed.

### PR DESCRIPTION
**Pull request by bartekn**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

This commit adds a code that handles Stellar-Core process exit gracefully. Added `processExit` unbuffered channel to `stellarCoreRunner` that receives the error in case Stellar-Core crashed or was terminated with an error or nil error if it was shutdown gracefully. The channel is later used in `PrepareRange` that returns an error if the process was stopped while prepare was running and in `sendLedgerMeta` that adds error to a meta channel that will be read by one of the following `GetLedger` calls.

Close #2705.

### Why

Right now when Stellar-Core crashes, `CaptiveStellarCore` simply wait for the next ledger without restarting it.

### CODE REVIEW

File: exp/ingest/ledgerbackend/captive_core_backend.go [hunk 1]
```diff
@@ -199,25 +203,31 @@ func (c *CaptiveStellarCore) sendLedgerMeta(untilSequence uint32) {
...
-			return
-		}
-		select {
-		case <-c.stop:
+			// When `GetLedger` sees the error it will close the backend. We shouldn't
+			// close it now because there may be some ledgers in a buffer.
+			c.metaC <- metaResult{nil, err}
 			return
-		case c.metaC <- metaResult{meta, nil}:
 		}
```
Comment (bartekn) [inline exp/ingest/ledgerbackend/captive_core_backend.go:229]: I simplified this code. There's no need to check `c.stop` here because even we discard one result from `metaC` in `Close` to unblock it. So even if the code is waiting here, it will be unlocked by `Close`.

File: exp/ingest/ledgerbackend/captive_core_backend.go [hunk 2]
```diff
@@ -271,6 +286,20 @@ func (c *CaptiveStellarCore) PrepareRange(ledgerRange Range) error {
 	}
 
 	for {
+		select {
+		case <-c.shutdown:
+			return nil
```
Comment (abuiles) [inline exp/ingest/ledgerbackend/captive_core_backend.go:291]: @bartekn should we call `c.Close()` here too before returning - is seem like `sendLedgerMeta` could still be running on the goroutine

Comment (bartekn) [reply exp/ingest/ledgerbackend/captive_core_backend.go:302]: No, because `c.shutdown` can be only closed by calling `Close`. So it implies that `Close` was called.
