### PR TITLE
services/horizon: Ignore db.ErrCanceled and ctx.Canceled returned by verifyState.

### LINKED ISSUE #2224: Ignore ErrCanceled errors returned by verifyState
### What did you do?

Horizon shutdown during state verification.

### What did you expect to see?

No errors.

### What did you see instead?

```
WARN[2020-02-04T18:14:19.987+01:00] State verification errored                    err="addAccountsToStateVerifier failed: Error running history.Q.GetAccountsByIDs: select failed: context canceled" pid=99452 service=expingest
```

Looks like we should add similar condition like in:
https://github.com/stellar/go/blob/6af401e1629e3a4a45f656c0c91ad0dd58952516/services/horizon/internal/expingest/main.go#L238-L246

Seems like it's a simple fix but we're going to release beta really soon so adding to stable milestone.

### PR DESCRIPTION
**Pull request by abuiles**
<details>
  <summary>PR Checklist</summary>

### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Ignore db.ErrCanceled and ctx.Canceled returned by verifyState.

Fix #2224

### Why

If the system is shutdown during state verification, there is a warning inthe log showing

``` WARN[2020-02-04T18:14:19.987+01:00] State verification errored
err="addAccountsToStateVerifier failed: Error running history.Q.GetAccountsByIDs: select failed: context canceled" pid=99452 service=expingest
```

If the system is being shutdown gracefully which is the case when we
get this errors, then we shouldn't log an error.

Fix #2224

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by abuiles** [comment]
@bartekn I added the helper.

File: services/horizon/internal/expingest/main.go [hunk 1]
```diff
@@ -429,3 +431,12 @@ func markStateInvalid(historyQ history.IngestionQ, err error) {
 		log.WithField("err", err).Error(updateExpStateInvalidErrMsg)
 	}
 }
+
+func isCancelledError(err error) bool {
+	cause := errors.Cause(err)
+	if err == nil {
+		return false
+	}
+
```
Comment (bartekn) [inline services/horizon/internal/expingest/main.go]: Looks like `Cause` [checks](https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/errors.go#L280) this internally.
```suggestion
```
