### PR TITLE
restore trades for account endpoint

### LINKED ISSUE #264: /accounts/<accountId>/trades broken
does not show sold_amount, sold_asset_type, bought_amount, bought_asset_type, offer_id

### PR DESCRIPTION
**Pull request by tomerweller**
closes #264 

for a clean diff without the generated code: https://github.com/stellar/go/pull/417/commits/b36007547702467a55500f44622742e51c55e755

### CODE REVIEW

File: services/horizon/internal/db2/history/trade.go [hunk 1]
```diff
@@ -66,6 +66,18 @@ func (q *TradesQ) forAssetPair(baseAssetId int64, counterAssetId int64) *TradesQ
...
 
+//filter Trades by account id
+func (q *TradesQ) ForAccount(aid string) *TradesQ {
+	var account Account
+	q.Err = q.parent.AccountByAddress(&account, aid)
+	if q.Err != nil {
+		return q
+	}
+
+	q.sql = q.sql.Where("htrd.base_account_id = ? OR htrd.counter_account_id = ?", account.ID, account.ID)
```
Comment (nullstyle) [inline services/horizon/internal/db2/history/trade.go]: The is not the right account filtering.  "Trades by account" should mean "trades in which the account was either the buyer or the seller", not "trades involving a currency issued by the account"

Comment (nullstyle) [reply services/horizon/internal/db2/history/trade.go]: ah, my bad.
