### PR TITLE
Fix paging links format in trade aggregation.

### LINKED ISSUE #160: Fix trade aggregation paging links format
Paging Links are currently paths and not fully qualified URLs. 
Scheme and host name should be added to conform to the rest of the API.

### PR DESCRIPTION
**Pull request by tomerweller**
Closes #160

### CODE REVIEW

**Comment by tomerweller** [comment]
@nullstyle The links are followed through and tested in the old tests. I added a small test to make sure the next link begins with 'http' because the `RequestHelper` is happy with both paths and fully qualified urls.

File: services/horizon/internal/actions_trade.go [hunk 1]
```diff
@@ -169,14 +169,15 @@ func (action *TradeAggregateIndexAction) loadPage() {
...
 
-	action.Page.BaseURL = action.BaseURL()
-	action.Page.BasePath = action.Path()
 	action.Page.Limit = action.PagingParams.Limit
 	action.Page.Order = action.PagingParams.Order
 
-	q := action.R.URL.Query() //build on top of existing query params, this takes care of all the filters
-	base := action.Page.BasePath
-	action.Page.Links.Self = hal.NewLink(base + "?" + q.Encode())
+	newUrl := action.BaseURL() // preserve scheme and host for the new url links
```
Comment (nikhilsaraf) [inline services/horizon/internal/actions_trade.go]: style suggestion: could we move the creation of `newUrl` into a separate function so it is *immutable* by this piece of code? (preferably as a function on `URL`).

also, `newUrl` is a very generic name and it's hard to tell what it represents without digging into this logic, can we use something more descriptive like `fullUrl`?

File: services/horizon/internal/actions_trade.go [hunk 2]
```diff
@@ -188,15 +189,16 @@ func (action *TradeAggregateIndexAction) loadPage() {
 				newStartTime = action.EndTimeFilter.ToInt64()
 			}
 			q.Set("start_time", strconv.FormatInt(newStartTime, 10))
-			action.Page.Links.Next = hal.NewLink(base + "?" + q.Encode())
-
+			newUrl.RawQuery = q.Encode()
+			action.Page.Links.Next = hal.NewLink(newUrl.String())
```
Comment (nikhilsaraf) [inline services/horizon/internal/actions_trade.go]: could we avoid mutating newUrl here too. Maybe put this in another function on `URL` where we can call it like this?:
`encodedUrl := newUrl.encodeRawQuery()`

File: services/horizon/internal/actions_trade_test.go [hunk 3]
```diff
@@ -159,6 +160,8 @@ func TestTradeActions_Aggregation(t *testing.T) {
 	//test that next page delivers the correct amount of records
 	w = ht.GetWithParams(aggregationPath, q)
 	nextLink = ht.UnmarshalNext(w.Body)
+	//make sure the next link is a full url and not just a path
+	ht.Assert.Equal(true, strings.HasPrefix(nextLink, "http"))
```
Comment (nikhilsaraf) [inline services/horizon/internal/actions_trade_test.go]: Would prefer an equality check on the full link url rather than a prefix assertion if possible.
If not possible, would be better if this could include the domain as well? `http://localhost`.

File: services/horizon/internal/actions_trade.go (hunk 1 above)
Comment (tomerweller) [reply services/horizon/internal/actions_trade.go]: This code works by mutating `newUrl` into the desired links. It's not pretty and I'm down with moving this out to a new immutable url type.

With that said, this is a fix for trading aggregation, I'd rather defer infra work to #148.

File: services/horizon/internal/actions_trade.go (hunk 2 above)
Comment (tomerweller) [reply services/horizon/internal/actions_trade.go]: Again, I'd rather defer infra work to #148.

**Comment by nullstyle** [comment]
@nikhilsaraf We probably just need to rewrite the horizon tests to use the `stellar/go/support/http/httptest` package.  Given that it leverages the `net/http/httptest` package, moving should eliminate discrepancies between test and real requests.
