### PR TITLE
Fix empty memo field in JSON when memo_type is text

### LINKED ISSUE #149: JSON: Memo: An empty "memo" is not being generated for a transaction even if "memo_type" is "text"
I'm going to start with an example JSON returned from Horizon using the following transaction:

[1113f23c225495534b2fd589a037798155ea73ee68a418e74364c1a3be4a20d8](https://horizon.stellar.org/transactions/1113f23c225495534b2fd589a037798155ea73ee68a418e74364c1a3be4a20d8
)

JSON:
```
{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/transactions/1113f23c225495534b2fd589a037798155ea73ee68a418e74364c1a3be4a20d8"
    },
    "account": {
      "href": "https://horizon.stellar.org/accounts/GALPCCZN4YXA3YMJHKL6CVIECKPLJJCTVMSNYWBTKJW4K5HQLYLDMZTB"
    },
    "ledger": {
      "href": "https://horizon.stellar.org/ledgers/7871"
    },
    "operations": {
      "href": "https://horizon.stellar.org/transactions/1113f23c225495534b2fd589a037798155ea73ee68a418e74364c1a3be4a20d8/operations{?cursor,limit,order}",
      "templated": true
    },
    "effects": {
      "href": "https://horizon.stellar.org/transactions/1113f23c225495534b2fd589a037798155ea73ee68a418e74364c1a3be4a20d8/effects{?cursor,limit,order}",
      "templated": true
    },
    "precedes": {
      "href": "https://horizon.stellar.org/transactions?order=asc\u0026cursor=33805687590912"
    },
    "succeeds": {
      "href": "https://horizon.stellar.org/transactions?order=desc\u0026cursor=33805687590912"
    }
  },
  "id": "1113f23c225495534b2fd589a037798155ea73ee68a418e74364c1a3be4a20d8",
  "paging_token": "33805687590912",
  "hash": "1113f23c225495534b2fd589a037798155ea73ee68a418e74364c1a3be4a20d8",
  "ledger": 7871,
  "created_at": "2015-10-01T04:17:31Z",
  "source_account": "GALPCCZN4YXA3YMJHKL6CVIECKPLJJCTVMSNYWBTKJW4K5HQLYLDMZTB",
  "source_account_sequence": "12884901893",
  "fee_paid": 100,
  "operation_count": 1,
  "envelope_xdr": "AAAAABbxCy3mLg3hiTqX4VUEEp60pFOrJNxYM1JtxXTwXhY2AAAAZAAAAAMAAAAFAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAJAAAAAAAAAAHwXhY2AAAAQGCy99saUm6alXIRyp0NNh2OFSCybp1JGPDN2pb/+Fw07/X7y4lPEp/B6WIV130a+2eY+5T3ujbiKa6TIcUaNwQ=",
  "result_xdr": "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAAJAAAAAAAAAAEAAAAAH6Ue1GOPj6Hb/ROPyIFCJpQPMujihEIvJSfK0UfMDIgAAK11sXTKRwAAAAA=",
  "result_meta_xdr": "AAAAAAAAAAEAAAACAAAAAwAAHrcAAAAAAAAAAB+lHtRjj4+h2/0Tj8iBQiaUDzLo4oRCLyUnytFHzAyIAACtdb1ePEoAAB6hAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAHr8AAAAAAAAAAB+lHtRjj4+h2/0Tj8iBQiaUDzLo4oRCLyUnytFHzAyIAAFa627TBpEAAB6hAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA",
  "fee_meta_xdr": "AAAAAgAAAAMAAB63AAAAAAAAAAAW8Qst5i4N4Yk6l+FVBBKetKRTqyTcWDNSbcV08F4WNg3gtrN3tPO0AAAAAwAAAAQAAAAAAAAAAQAAAAAfpR7UY4+Podv9E4/IgUImlA8y6OKEQi8lJ8rRR8wMiAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAAB6/AAAAAAAAAAAW8Qst5i4N4Yk6l+FVBBKetKRTqyTcWDNSbcV08F4WNg3gtrN3tPNQAAAAAwAAAAUAAAAAAAAAAQAAAAAfpR7UY4+Podv9E4/IgUImlA8y6OKEQi8lJ8rRR8wMiAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==",
  "memo_type": "text",
  "signatures": [
    "YLL32xpSbpqVchHKnQ02HY4VILJunUkY8M3alv/4XDTv9fvLiU8Sn8HpYhXXfRr7Z5j7lPe6NuIprpMhxRo3BA=="
  ]
}
```

Notice there is the "memo_type" element with the value of "text". This suggests there should be a "memo" element somewhere(because client SDKs don't allow null memos of type text). If we decode the envelope_xdr we can see there is indeed a MemoText in there, with a value of empty string.

This will cause issues when client SDKs try to deserialize this transaction from JSON. I have tested this in the official java-stellar-sdk and it does indeed throw a null reference exception.

### PR DESCRIPTION
**Pull request by lechengfan**
- resolves #149, where the "memo" field does not exist in the JSON response for a transaction whose memo_type is text and the memo happens to be an empty string.
- Fix is to define a custom JSON marshaler that converts the Memo field to be a string pointer. That way if the memo_type is none, it can be set to nil and the resulting JSON response doesn't have a memo field. In all other cases, it points to a string (possibly the empty string), which would cause the JSON response to include "memo" as a field.
- Add some test cases to ensure this behavior, and also make sure that the default marshalling and unmarshalling of Transactions still work.

### CODE REVIEW

**Comment by kr** [comment]
> points to an empty string which would cause the JSON response to have "memo": "" as a field

For the sake of precision, maybe we can change the description to say 'points to a string (possibly the empty string), which would cause the JSON response to have "memo" as a field'.

File: protocols/horizon/main.go [hunk 1]
```diff
@@ -372,6 +373,20 @@ type Transaction struct {
 	ValidBefore     string    `json:"valid_before,omitempty"`
 }
 
+func (t Transaction) MarshalJSON() ([]byte, error) {
```
Comment (bartekn) [inline protocols/horizon/main.go]: Please add a short comment explaining why we need this method.

I'm also wondering if we should change `Memo` field tag on `Transaction` to `json:"-"` to avoid confusion.

File: protocols/horizon/main_test.go [hunk 2]
```diff
@@ -49,3 +50,50 @@ func TestAccount(t *testing.T) {
 		})
 	})
 }
+
+func TestTransactionJSONMarshal(t *testing.T) {
+	Convey("After marshalling and unmarshalling, the resulting struct should be the exact same as the original", t, func() {
```
Comment (bartekn) [inline protocols/horizon/main_test.go]: This is not written down anywhere (👎 for us) but we want to remove `github.com/smartystreets/goconvey` dependency so it's better to write all new tests using `Test...` functions and `assert`, `mock`, etc. packages from `github.com/stretchr/testify`.

**Comment by bartekn** [comment]
PS: please use [GH closing tags](https://help.github.com/articles/closing-issues-using-keywords/) to automatically close issues.

File: protocols/horizon/main_test.go [hunk 3]
```diff
@@ -51,49 +52,47 @@ func TestAccount(t *testing.T) {
...
-		So(marshalErr, ShouldBeNil)
-		var result struct {
-			Memo *string
-		}
-		json.Unmarshal(marshaledTransaction, &result)
-		if result.Memo != nil {
-			t.Errorf("MemoType is none, but memo is not nil")
-		}
-	})
+// If a transaction's memo type is None, then memo field should be nil in JSON
```
Comment (kr) [inline protocols/horizon/main_test.go]: Nit: s/should be nil in/should be omitted from/
