### PR TITLE
Use the updated ledger state in ingest

### LINKED ISSUE #513: duplicate key value violates unique constraint "hist_e_by_order"
```
{"hostname":"horizon-001a","level":"error","message":"import session failed: Ingestion.Flush error: Error adding values while inserting to history_effects: Error adding values while inserting to history_effects: exec failed: pq: duplicate key value violates unique constraint "hist_e_by_order"","pid":2811,"timestamp":"2018-06-19T13:29:12.191629049Z"}
```

### PR DESCRIPTION
**Pull request by bartekn**
This PR fixes random DB constraint errors like (and similar):
```
import session failed: Ingestion.Flush error: Error adding values while inserting to history_effects: Error adding values while inserting to history_effects: exec failed: pq: duplicate key value violates unique constraint "hist_e_by_order"
```
The reason is a synchronization issue between `App.UpdateLedgerState` and `ingest.System.runOnce` go routines. Both go routines are executed every second by the application ticker. The following sequence of events is possible:

Time | Tick1 | Tick2
-|-|-
1 | `UpdateLedgerState` result = `[horizon ledger = 10, core ledger = 11]` |
2 | Start ingest session `ledgers: [11, 11]` |
3 | | `UpdateLedgerState` result = `[horizon ledger = 10, core ledger = 11]`
4 | Finish ingest session `ledgers: [11, 11]` |
5 | | Start ingest session `ledgers: [11, 11]`
6 | | Error in ingest session `ledgers: [11, 11]` (because already saved in t=4)

So it is possible that `ingest.System.runOnce` reads the stale state of ledgers. The simple fix in this PR moves loading the state to `ingest.System.runOnce`. The long-term fix, in my opinion, should remove synchronization requirement in `ingest` package (use internal state only, use infinite `for` instead of ticker etc.).

Close #513.

PS. I've been searching for this for so long! It feels good! 🤓

### CODE REVIEW

File: services/horizon/internal/ingest/system.go [hunk 1]
```diff
@@ -241,6 +239,24 @@ func (i *System) runOnce() {
 	is := i.current
 	i.lock.Unlock()
 
+	// Warning: do not check the current ledger state using ledger.CurrentState()! It is updated
+	// in another go routine and can return the same data for two different ingesiton sessions.
```
Comment (robertDurst) [inline services/horizon/internal/ingest/system.go]: ingesiton -> ingestion

**Comment by bartekn** [comment]
Fortunately, I found a possible deadlock and fixed it in 79e453a. Deadlock was possible when one of the DB queries errors (this did not set `i.current = nil` and making a new ingest sessions impossible). We should really do: #613.
