### PR TITLE
exp/ingest: Fix fee and transaction meta processing

### LINKED ISSUE #2038: services/horizon/expingest: False positive from StateVerifier
### What version are you using?

Horizon 0.23.1, 0.24.0 RC

### What did you do?

After processing pubnet checkpoint ledger [27207615](https://horizon.stellar.org/ledgers/27207615) state verification failed after a couple seconds with the following error:
```
addAccountsToStateVerifier failed: Entry does not match the fetched entry. Expected: AZ8nvwAAAAAAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcJOKW6QDjhboAAH7VAAAAAAAAAAEAAAAAnaQ/bEto5UuPoNHBfWYzIDSa5tidi+7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA== (pretransform = AZ8nvwAAAAAAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcJOKW6QDjhboAAH7VAAAAAAAAAAEAAAAAnaQ/bEto5UuPoNHBfWYzIDSa5tidi+7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==), actual: AZ8nvwAAAAAAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcEWT3KQDjhboAAH7VAAAAAAAAAAEAAAAAnaQ/bEto5UuPoNHBfWYzIDSa5tidi+7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
```
XDR view: [expected](https://www.stellar.org/laboratory/#xdr-viewer?input=AZ8nvwAAAAAAAAAADq%2BQhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcJOKW6QDjhboAAH7VAAAAAAAAAAEAAAAAnaQ%2FbEto5UuPoNHBfWYzIDSa5tidi%2B7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&type=LedgerEntry&network=public), [actual](https://www.stellar.org/laboratory/#xdr-viewer?input=AZ8nvwAAAAAAAAAADq%2BQhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcEWT3KQDjhboAAH7VAAAAAAAAAAEAAAAAnaQ%2FbEto5UuPoNHBfWYzIDSa5tidi%2B7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&type=LedgerEntry&network=public).

This occurred in multiple Horizon servers after processing the ledger above.

The difference seems to be due to transaction [`ea1e9...30f6a`](https://horizon.stellar.org/transactions/ea1e96dd4aa8a16e357842b0fcdb66c1ab03fade7dcd3a99f88ed28ea8c30f6a). The difference in account balance is 32.7 XLM. After checking the database state manually the balance of the account above was correct. After marking the state as valid manually (`exp_state_invalid=false` in `key_value_store`) the consecutive state verifications did not find any differences between DB state and state in history archive.

### PR DESCRIPTION
**Pull request by bartekn**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

This commit changes `io.LedgerTransaction` to return fee and tx meta separately and updates Horizon processors to apply changes in correct order. This issue was found by `StateVerifier`.

Close #2038.

### Why

The order of applying meta changes in Horizon processors was incorrect. Fee changes must be applied before everything else. In other words instead of processing meta like:
```
TX1_FEE_META, TX1_TX_META, TX2_FEE_META, TX2_TX_META, ...
```
we should do it like:
```
TX1_FEE_META, TX2_FEE_META, TX1_TX_META, TX2_TX_META, ...
```

### Known limitations

As you can see the current interface of pipeline processor doesn't make sense because all transactions need to be read into memory first to apply fee changes. We either need to refactor the processors or use @tamirms design where pipeline is removed (I'm leaning toward the latter). I'll create an issue about this tomorrow.

### CODE REVIEW

File: services/horizon/internal/expingest/main.go [hunk 1]
```diff
@@ -39,7 +39,9 @@ const (
 	//      when preauth tx is failed.
 	// - 9: Fixes a bug in asset stats processor that counted unauthorized
 	//      trustlines.
-	CurrentVersion = 9
+	// - 9: Fixes a bug in meta processing (fees are now processed before
```
Comment (bartekn) [inline services/horizon/internal/expingest/main.go]:
```suggestion
	// - 10: Fixes a bug in meta processing (fees are now processed before
```

**Comment by tamirms** [comment]
@bartekn how did you determine what the correct order of operations is? did you get this information from reading stellar core? would it be worth having someone from the stellar core team to review the ledger processor at a high level?

**Comment by bartekn** [comment]
> how did you determine what the correct order of operations is? did you get this information from reading stellar core?

I read [this](https://github.com/stellar/stellar-core/blob/master/docs/integration.md) doc one more time and realized my understanding of the order is incorrect (actually added a PR to make it less confusing: https://github.com/stellar/stellar-core/pull/2366). It was also confirmed by @jonjove in Slack. And finally state verification of for the range that failed before works now.
