### PR TITLE
services/horizon: Use XFFMiddleware in Horizon

### LINKED ISSUE #3301: Remove xff middleware
[`xff`](https://github.com/stellar/go/blob/013bf861cb0f060be1e2c1b0fdf4cb12a00d6b9d/services/horizon/internal/httpx/router.go#L79) middleware replaces the `RemoteAddr` but doesn't work correctly in ELB which appends client IP to `X-Forwarder-For` (instead of prepending as most proxies do). We should create a new middleware with an option to overwrite `RemoteAddr` with first/last IP in `X-Forwarder-For` (depends on a feature flag). Additionally, we should log entire `X-Forwareded-For` header value. If header value is too long (TBD), Horizon should return `400 Bad Request`.

### PR DESCRIPTION
**Pull request by bartekn**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Use `XFFMiddleware` (added in #3460) in Horizon.

Close #3301.

### Why

Previously used `github.com/sebest/xff` did not work correctly in some environments.

### Known limitations

[TODO or N/A]

### CODE REVIEW

File: services/horizon/internal/middleware_test.go [hunk 1]
```diff
@@ -131,10 +131,6 @@ func (suite *RateLimitMiddlewareTestSuite) TestRateLimit_XForwardedFor() {
 	w = suite.rh.Get("/", requestHelperRemoteAddr("4.4.4.3"))
 	assert.Equal(suite.T(), 200, w.Code)
 
-	// Ignores leading private ips
-	w = suite.rh.Get("/", requestHelperXFF("10.0.0.1, 4.4.4.4"))
-	assert.Equal(suite.T(), 429, w.Code)
```
Comment (bartekn) [inline services/horizon/internal/middleware_test.go:136]: Removed this test because in some cases (like AWS) this is fine because client IP is appended, not prepended.

**Review by tamirms — APPROVED** [review]
