### PR TITLE
Require migration to run Horizon version successfully (fixes #778)

### LINKED ISSUE #778: Exit Horizon if DB has not been migrated to required version
Why horizon isn't auto-migrating DB schema when you start a new version?

E.g. when you start `v0.15.2` and previously you had `v0.14.2` it will fail on updating history until you do manually `./horizon db migrate up`.

I don't get why you do not build migration mechanism into the daemon itself or do not start horizon at all (signaling that you need to migrate DB schema) if DB is not in an actual state?

Thanks.

### PR DESCRIPTION
**Pull request by ire-and-curses**
When a user runs a newer or older version of Horizon that is incompatible with the current DB state, Horizon should fail with a descriptive error message indicating the migration(s) that need to be performed, and their direction. This avoids the situation described in #778, where Horizon may run in a broken way without alerting the user.

We do not run the migration automatically, since the user should understand what is happening, and take responsibility for backing up their data if necessary.

Example command line output when a new migration is detected:

```
$horizon --db-url="postgres://localhost/horizon_schema" --stellar-core-db-url="postgres://stellar:postgres@localhost:8002/core" --stellar-core-url="http://localhost:11626" --port 8001 --network-passphrase "Test SDF Network ; September 2015" --ingest
2019/01/11 16:39:11 A database migration is required to run this version (devel) of Horizon. Run "horizon db migrate DIRECTION" to update your DB. Consult the Changelog (https://github.com/stellar/horizon/blob/master/CHANGELOG.md) for more information.
2019/01/11 16:39:11 There are 1 migrations to apply in the "up" direction
2019/01/11 16:39:11 The necessary migrations are:
2019/01/11 16:39:11     15_made_up_stuff.sql
```

### CODE REVIEW

File: services/horizon/internal/db2/schema/main.go [hunk 1]
```diff
@@ -68,3 +69,68 @@ func Migrate(db *sql.DB, dir MigrateDir, count int) (int, error) {
 		return 0, errors.New("Invalid migration direction")
 	}
 }
+
+// Find the names of any migrations needed in the "up" or "down" directions
```
Comment (bartekn) [inline services/horizon/internal/db2/schema/main.go]: In Go, [comments](https://golang.org/doc/effective_go.html#commentary) should start with a name being declared:
> The first sentence should be a one-sentence summary that starts with the name being declared.

File: services/horizon/internal/db2/schema/main.go [hunk 2]
```diff
@@ -68,3 +69,68 @@ func Migrate(db *sql.DB, dir MigrateDir, count int) (int, error) {
...
+	dir := directions[dirStr]
+	possibleMigrations, _, migrateErr := migrate.PlanMigration(db, "postgres", Migrations, dir, 0)
+	if migrateErr != nil {
+		stdLog.Fatal(migrateErr)
+	}
+
+	// Extract a list of the possible migration names
+	var possibleIds []string
+	for _, m := range possibleMigrations {
+		possibleIds = append(possibleIds, (*m).Id)
```
Comment (bartekn) [inline services/horizon/internal/db2/schema/main.go]: In Go getting values from pointers to struct automatically dereferences it, so it's OK to write `m.Id`. It's just shorter. [play.golang](https://play.golang.org/p/DxWzRHluiqN) example.

File: services/horizon/internal/db2/schema/main.go [hunk 3]
```diff
@@ -68,3 +69,68 @@ func Migrate(db *sql.DB, dir MigrateDir, count int) (int, error) {
...
+	}
+
+	// Get the set of migrations recorded in the database
```
Comment (bartekn) [inline services/horizon/internal/db2/schema/main.go]: Doesn't [`PlanMigration`](https://github.com/rubenv/sql-migrate/blob/master/migrate.go#L445) do the same thing as everything below? I tested this locally (removed a few last migrations from `gorp_migrations` table) and it returned exactly the list of missing migrations.

Also, when `dir` param is `Down` and `max` is `0` it will return all migrations to remove. I think we shouldn't check this for down-migrations, in general people should never downgrade Horizon version.

Comment (ire-and-curses) [reply services/horizon/internal/db2/schema/main.go]: Yes, `PlanMigration` is enough for the `Up` case. My original implementation did this. All the extra differencing is to handle the `Down` case correctly. I talked it over with Tom and we thought there might be a case for this during development, or if a bad update happened, or if an old version of Horizon was accidentally started.

There is also the edge case of migrations that are missing, between the start and the end. If you use only `PlanMigration`, I think you may still need to get the list of applied migrations from the DB to find the specific migrations that were not done yet (but I haven't tested this).

Would you prefer me to simplify the code and just handle the `Up` case?

Comment (tomquisel) [reply services/horizon/internal/db2/schema/main.go]: To weigh in, I think it's smart to handle the down case as well. It's valuable to catch developers who've gone off the rails, rather than let them struggle in cases where they may have accidentally downgraded and are using the wrong version of Horizon for their DB.

Comment (bartekn) [reply services/horizon/internal/db2/schema/main.go]: OK, at first I wanted to agree with you but then I started checking if it's possible to simplify the `down` case code a bit and I realised that it will not work so easy.

Let's say I have two binaries Horizon V1 and Horizon V2. I've just deployed V2 but realized I don't like it so I want to `migrate down` DB. Now, if I run Horizon V1 it will tell me to migrate down but I can't do it because Horizon V1 does not contain V2 migrations SQL code. Horizon V2 will not complain at all as all migrations required by this version are applied. What you need to do is use V2 to actually migrate db down using the information that V1 gave you.

I think for recovering from bad deploys Horizon admin should check how many migrations were applied (`horizon db migrate up` will output the number of migrations - let's say: `X`) and if migrating down is required they can use this number in `horizon db migrate down X` command.

If you think we need this I'm OK but we need to update the output to explain how to deal with migrations when migrating down using 2 binaries.

> There is also the edge case of migrations that are missing, between the start and the end. If you use only PlanMigration, I think you may still need to get the list of applied migrations from the DB to find the specific migrations that were not done yet (but I haven't tested this).

I think we shouldn't worry about this. Horizon will never leave migrations in such state (i.e. no gaps possible between migrations). And it's not possible to deal with all changes to DB that users made manually.

Comment (tomquisel) [reply services/horizon/internal/db2/schema/main.go]: Ok, great points Bartek. Agreed we shouldn't worry about case of gaps. Updating the error output for the `down` case to explain that the user needs to use the newest binary to run the migrate down sounds low effort and gives us some extra safety vs. just erroring in the `up` case. I'm good for that approach.

File: services/horizon/internal/db2/schema/main.go [hunk 4]
```diff
@@ -68,3 +69,68 @@ func Migrate(db *sql.DB, dir MigrateDir, count int) (int, error) {
...
+	}
+
+	// Extract a list of names of the previously applied migrations
+	var migrationRecordIds []string
+	for _, m := range migrationRecords {
+		migrationRecordIds = append(migrationRecordIds, (*m).Id)
+	}
+
+	// Find any migrations that need to be applied in this direction
+	migrationsToApply := difference(possibleIds, migrationRecordIds)
```
Comment (howardtw) [inline services/horizon/internal/db2/schema/main.go]: nit: we can just do `return difference(possibleIds, migrationRecordIds)` here

File: services/horizon/main.go [hunk 5]
```diff
@@ -239,6 +241,24 @@ func initConfig() {
 		stdLog.Fatal("Invalid config: stellar-core-url is blank.  Please specify --stellar-core-url on the command line or set the STELLAR_CORE_URL environment variable.")
 	}
 
+	migrationsToApplyUp := schema.GetMigrationsUp(viper.GetString("db-url"))
+	if len(migrationsToApplyUp) > 0 {
+		stdLog.Printf("There are %v migrations to apply in the \"up\" direction.", len(migrationsToApplyUp))
+		stdLog.Printf("The necessary migrations are:")
```
Comment (howardtw) [inline services/horizon/main.go]: Maybe we can just do
```
stdLog.Printf("The necessary migrations are: %v\n", migrationsToApplyUp)
```
What's better is that we can just combine the three `stdLog.Printf` calls. Same for MigrationsDown.

File: services/horizon/internal/db2/schema/main.go [hunk 6]
```diff
@@ -68,3 +69,55 @@ func Migrate(db *sql.DB, dir MigrateDir, count int) (int, error) {
...
+	}
+
+	return migrationNames
+}
+
+// GetMigrationsDown returns the number of migrations to apply in the
+// "down" direction  to return to the older schema version expected by this
+// version of Horizon. To keep the code simple, it does not provide a list of
+// migration names.
+func GetMigrationsDown(dbUrl string) (nMigrations int) {
```
Comment (howardtw) [inline services/horizon/internal/db2/schema/main.go]: Can we rename the function to something like `GetNumMigrationsDown` or `GetMigrationsDownLen` so that we know we are getting the length of the migrations? The behavior of `GetMigrationsUp` and `GetMigrationsDown` is inconsistent.

File: services/horizon/internal/db2/schema/main.go [hunk 7]
```diff
@@ -68,3 +69,55 @@ func Migrate(db *sql.DB, dir MigrateDir, count int) (int, error) {
...
+
+	// Get the possible migrations
+	possibleMigrations, _, migrateErr := migrate.PlanMigration(db, "postgres", Migrations, migrate.Up, 0)
+	if migrateErr != nil {
+		stdLog.Fatal(migrateErr)
+	}
+
+	// Extract a list of the possible migration names
+	for _, m := range possibleMigrations {
+		migrationNames = append(migrationNames, m.Id)
```
[the remark this answers is not in the document]
Comment (ire-and-curses) [reply services/horizon/internal/db2/schema/main.go]: Yeah. I named them `name` because they are actually human-readable strings that describe the migration. But the migration library calls them `Ids`, based on the DB column I guess. We can change them if you prefer.

File: services/horizon/main.go [hunk 8]
```diff
@@ -239,6 +241,24 @@ func initConfig() {
 		stdLog.Fatal("Invalid config: stellar-core-url is blank.  Please specify --stellar-core-url on the command line or set the STELLAR_CORE_URL environment variable.")
 	}
 
+	migrationsToApplyUp := schema.GetMigrationsUp(viper.GetString("db-url"))
+	if len(migrationsToApplyUp) > 0 {
+		stdLog.Printf("There are %v migrations to apply in the \"up\" direction.", len(migrationsToApplyUp))
```
[the remark this answers is not in the document]
Comment (ire-and-curses) [reply services/horizon/main.go]: Backticks don't interpret \n, do they? In any case we get a new line from the logger.

File: services/horizon/internal/db2/schema/main.go (hunk 6 above)
Comment (ire-and-curses) [reply services/horizon/internal/db2/schema/main.go]: Yeah, can do. I thought about that. I thought the naming symmetry was more important because the compiler would immediately point out the difference in return type, and the two cases are truly asymmetric (down doesn't have a list that makes sense without a lot of differencing work). But I'm happy to change it. :)

Comment (ire-and-curses) [reply services/horizon/internal/db2/schema/main.go]: (this is actually why I did the original implementation with the extra differencing - to maintain symmetry across both directions)

File: services/horizon/internal/db2/schema/main.go [hunk 9]
```diff
@@ -68,3 +69,53 @@ func Migrate(db *sql.DB, dir MigrateDir, count int) (int, error) {
...
+
+	// Extract a list of the possible migration names
+	for _, m := range possibleMigrations {
+		migrationIds = append(migrationIds, m.Id)
+	}
+
+	return migrationIds
+}
+
+// GetMigrationsDown returns the number of migrations to apply in the
```
Comment (bartekn) [inline services/horizon/internal/db2/schema/main.go]: Function name not updated.

Comment (ire-and-curses) [reply services/horizon/internal/db2/schema/main.go]: thanks! fixed

File: services/horizon/main.go [hunk 10]
```diff
@@ -240,8 +242,23 @@ func initConfig() {
 		stdLog.Fatal("Invalid config: stellar-core-url is blank.  Please specify --stellar-core-url on the command line or set the STELLAR_CORE_URL environment variable.")
 	}
 
-	if viper.GetString("network-passphrase") == "" {
+  if viper.GetString("network-passphrase") == "" {
```
Comment (bartekn) [inline services/horizon/main.go]: Re: our formatting discussion, tabs instead of spaces. Created https://github.com/stellar/go/issues/819.
