### PR TITLE
fix trades account filter

### LINKED ISSUE #486: Trades for account endpoint: pagination doesn't work
Here's a sample call to get trades on an account:

https://horizon.stellar.org/accounts/GAH3MQ6IJZ7QA4LT657AGUTVR7H3B3QQKBZ4Y4FKIASU7USAO5QTMH2X/trades?limit=2&order=desc

The links look like this:

```.json

  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/accounts/GAH3MQ6IJZ7QA4LT657AGUTVR7H3B3QQKBZ4Y4FKIASU7USAO5QTMH2X/trades?cursor=\u0026limit=2\u0026order=desc"
    },
    "next": {
      "href": "https://horizon.stellar.org/accounts/GAH3MQ6IJZ7QA4LT657AGUTVR7H3B3QQKBZ4Y4FKIASU7USAO5QTMH2X/trades?cursor=78015765944496129-0\u0026limit=2\u0026order=desc"
    },
    "prev": {
      "href": "https://horizon.stellar.org/accounts/GAH3MQ6IJZ7QA4LT657AGUTVR7H3B3QQKBZ4Y4FKIASU7USAO5QTMH2X/trades?cursor=78081642152878081-0\u0026limit=2\u0026order=asc"
    }
  }
```

One thing looks wrong on its face: The "next" link is the same as the "prev" link with a different ordering mechanism, whereas you'd expect the difference to be different cursors.

Visiting the `next` link loads the same records as the initial call.

### PR DESCRIPTION
**Pull request by tomerweller**
add trades for account paging tests
closes #486

### CODE REVIEW

File: services/horizon/internal/actions_trade_test.go [hunk 1]
```diff
@@ -102,13 +103,36 @@ func TestTradeActions_Index(t *testing.T) {
 		ht.Assert.PageOf(2, w.Body)
 	}
 
-	w = ht.Get("/accounts/GCXKG6RN4ONIEPCMNFB732A436Z5PNDSRLGWK7GBLCMQLIFO4S7EYWVU/trades")
```
Comment (nullstyle) [inline services/horizon/internal/actions_trade_test.go]: We should still keep this test.
