### PR TITLE
Bifrost 0.0.2

### LINKED ISSUE #251: Bifrost: issuer_public_key is used to create new accounts
I have my issuer locked (master: 0) as instructed, so it would fail when creating the new account.

If there is a better optimal setup, please update the docs.

Also, acount_configurator.go for loop at 116.  It would have saved me a bunch of time debugging if it logged while waiting for trustlineExists.  I configured things incorrectly and just looped forever, a log would have helped debug the problem.  I can pull request if you want, but it's just one line.  Line 128 add

localLog.Info("Waiting for trustline...")

### LINKED ISSUE #267: bifrost: add support for timelocked accounts
Almost all ICOs have some sort of time-lock period, even if only for the duration of the sale.

Some issuers have used used `Authorization revocable` on their assets to achieve this. By revoking assets right after moving them and then un-revoking at the end of the sale. This is cumbersome and does not provide any transparency for the process.

I propose using multi-sig accounts and time locked transactions to achieve this. 

The gist: 
- The issuer will create an account and place the user's assets in it.
- The issuer will add the user as a signee on this account and adjust weights to be 2/2. 
- The issuer and the user will pre-sign a timlocked transaction to transfer full ownership to the user at the end of the sale.
- The user will be given a copy of this transaction. 
- Optionally, the issuer will save a copy of the transaction and will auto-submit it at the right time.

### LINKED ISSUE #350: add timebounds to transaction builder

### PR DESCRIPTION
**Pull request by bartekn**
🔥 Bifrost 0.0.2 is almost here! 🔥

New features:
* Configuring account has been moved to backend by adding a temporary signer on user's account. This makes the whole process much faster, easier to maintain and less error prone (only 1-2 recovery transactions needed).
* Time-locking account during a token sale. Close #267.
* Allows using Distribution account (ex. when Issuing account has been locked). Close #251.
* Automatically imports database schema when server is started (or asks to recreate DB if schema is out of date). We are not implementing schema migrations here because Bifrost deployments are short-lived (so #86 still open).
* "Account configuration" section in README.

And additionally it closes #350 because it was needed to create a transaction with time bounds.

### CODE REVIEW

File: services/bifrost/main.go [hunk 1]
```diff
@@ -355,18 +375,28 @@ func createServer(cfg config.Config, stressTest bool) *server.Server {
...
+		DistributionPublicKey: cfg.Stellar.DistributionPublicKey,
+		SignerSecretKey:       cfg.Stellar.SignerSecretKey,
+		NeedsAuthorize:        cfg.Stellar.NeedsAuthorize,
+		TokenAssetCode:        cfg.Stellar.TokenAssetCode,
+		StartingBalance:       cfg.Stellar.StartingBalance,
+		LockUnixTimestamp:     cfg.Stellar.LockUnixTimestamp,
 	}
 
 	if cfg.Stellar.StartingBalance == "" {
 		stellarAccountConfigurator.StartingBalance = "41"
```
[the remark this answers is not in the document]
Comment (bartekn) [reply services/bifrost/main.go]: Yes, this makes sense, thanks!

**Comment by bartekn** [comment]
> Got a question about LockUnixTimestamp. Does this have to be a timestamp in the future? If so do we test if the timestamp given meets that criteria?

We don't have any checks in place right now. We can do it but I think people can still enter a timestamp that is in a future but before the locking period ends by mistake. I'd be more concern by setting the value too far in a future (like 10 years ahead 😉) so it basically blocks assets for a long time.

**Comment by poliha** [comment]
Yes its definitely more serious if its too far in the future. I guess we can always add the checks in future iterations.

**Comment by bartekn** [comment]
@poliha added a new bullet in "Going to production" section of the README file.

File: services/bifrost/database/postgres.go [hunk 2]
```diff
@@ -98,6 +101,39 @@ func (d *PostgresDatabase) Open(dsn string) error {
 	return nil
 }
 
+// Import imports DB schema
+func (d *PostgresDatabase) Import() error {
+	return d.session.ExecAll(schema)
+}
+
+// GetSchemaVersion returns schema version of Bifrost DB. Returns 0.
+func (d *PostgresDatabase) GetSchemaVersion() (uint32, error) {
```
Comment (nullstyle) [inline services/bifrost/database/postgres.go]: If you are going to implement another schema migration system, this needs to be implemented as a support package that all of our monorepo services can depend upon.

Comment (nullstyle) [reply services/bifrost/database/postgres.go]: And you should probably retrofit horizon's migration system to ensure your common solution can handle both bifrost and horizon.

Comment (bartekn) [reply services/bifrost/database/postgres.go]: OK, it requires explanations. Bifrost is not a service that is run continuously for months, usually it's deployed during an ICO which lasts for a few days or weeks and it's later shut down. That's why I don't think it requires schema migration code because it's very unlikely that it will be upgraded during an ICO (what's more it shouldn't be). What we do here is we just ensure that schema version saved in a DB matches the current one Bifrost in case someone decides to upgrade it **before** starting an ICO.

Comment (nullstyle) [reply services/bifrost/database/postgres.go]: I'm fine with this explanation.  In the end I would prefer we have one codebase that can support both scenarios, but I'm fine with us pushing that to a later date.
