### PR TITLE
exp/ingest/io: Add StatsLedgerTransactionProcessor

### LINKED ISSUE #2208: Log number of changes, transactions and operations when ingesting ledgers
We should start logging number of changes, transactions and operations in `Processed ledger` log entries. This will help us better understand performance issues (if any). Additionally, the data can be broken down into:
* changes per type (created, updated, deleted),
* changes per ledger entry type (account, offer, ...),
* changes after using `LedgerEntryChangesCache`,
* operation type.

### PR DESCRIPTION
**Pull request by bartekn**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

This commit adds `exp/ingest/io.StatsLedgerTransactionProcessor` struct responsible for reporting transactions stats and adds it to Horizon processors.

Close #2208

### Why

Transaction stats are essential to understanding possible performance issues in ingestion process (if/as they happen).

### CODE REVIEW

File: services/horizon/internal/expingest/fsm.go [hunk 1]
```diff
@@ -825,5 +851,32 @@ func loggerWithChangeStats(stats io.StatsChangeProcessorResults) *logpkg.Entry {
 		"stats_trust_lines_created": stats.TrustLinesCreated,
 		"stats_trust_lines_updated": stats.TrustLinesUpdated,
 		"stats_trust_lines_removed": stats.TrustLinesRemoved,
-	})
+	}
+}
+
+func ledgerTransactionStatsFields(stats io.StatsLedgerTransactionProcessorResults) logpkg.F {
```
Comment (abuiles) [inline services/horizon/internal/expingest/fsm.go]: should this belong to `io.StatsLedgerTransactionProcessorResults`?

Comment (bartekn) [reply services/horizon/internal/expingest/fsm.go]: Good point! Fixed in https://github.com/stellar/go/pull/2273/commits/977d5fe3f1e331a0e4a5fdf0d034fefbc9a1024d.
