### PR TITLE
services/horizon: Change NewSeq attribute in SequenceBumped to be a string.

### LINKED ISSUE #1363: int64 in horizon JSON responses
Horizon uses int64 for some data types internally that end up in JSON resonses as numbers. One example is the entry `new_seq` in the `SequenceBumped` effect (see [1] for an example).

Since some int64 numbers cannot be represented as JavaScript numbers (which are 64 bit floating point) there is a risk of potential information loss.

As an example see the last effect in [1]. It is displayed as a bump to sequence number `90071992547409920` in the horizon response. However, the actual effect is a bump to sequence number `90071992547409923`. This becomes obvious when looking at the original transaction that created this sequence bump and decoding the XDR: [2].

Hence, the horizon response is wrong! The reason is that 90071992547409923 is not a valid JavaScript number and will be coerced to 90071992547409920.

[1] https://horizon-testnet.stellar.org/accounts/GB5L6RL523F72DBU6UEPI4VRPHYRISP46OWOYL2M324NNRVUPV76PQ6B/effects

[2] https://horizon-testnet.stellar.org/transactions/a1dfac3f3a7b6aa753c20f03450c4559cdfc5311e71a71111e42db183cd2711a

### PR DESCRIPTION
**Pull request by abuiles**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [X] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ X] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [X] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`

### Thoroughness

* [X] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### Summary
Change data type for field `NewSeq` in `SequenceBumped` effect from `int64` to `string.` Fixes #1363.

### Goal and scope

Update horizon's `JSON `response for field `new_seq` in `NewSequenceBumped` effect to return a `string` instead of an `int64`. Using an `int64` produces inconsistent results for clients using `JavaScript` since some `int64 `numbers cannot be represented as JavaScript numbers.

### Summary of changes
1. Add a new struct to represent `SequenceBumped` at the database (`history`) level.
2. Update the `effects` resource adapter to use the new struct when parsing the `jsonb` in effects and then pass the value as a string to the horizon representation of effect.

### Known limitations & issues

This will likely break clients who are expecting an `int64` instead of a `string`.

### What shouldn't be reviewed

N/A

### CODE REVIEW

File: services/horizon/internal/db2/history/main.go [hunk 1]
```diff
@@ -162,6 +163,12 @@ type Effect struct {
 	DetailsString      null.String `db:"details"`
 }
 
+// SequenceBumped is a struct of data from `effects.DetailsString`
+// when the effect type is sequence bumped.
+type SequenceBumped struct {
```
Comment (abuiles) [inline services/horizon/internal/db2/history/main.go]: Before we were using the horizon struct to interact directly with the DB. This give us a intermediate struct that we can use to interact with the raw data in the db.

File: services/horizon/CHANGELOG.md [hunk 2]
```diff
@@ -12,6 +12,10 @@ bumps.  A breaking change will get clearly notified in this log.
 * Add experimental path finding endpoint which uses an in memory order book for improved performance. To enable it set `--enable-experimental-ingestion` CLI param or `ENABLE_EXPERIMENTAL_INGESTION=true` env variable. Note that the `enable-experimental-ingestion` flag enables both the new path finding endpoint and the accounts for signer endpoint.
 * `--enable-accounts-for-signer` CLI param or `ENABLE_ACCOUNTS_FOR_SIGNER=true` env variable are merged with `--enable-experimental-ingestion` CLI param or `ENABLE_EXPERIMENTAL_INGESTION=true` env variable.
 
+### Breaking changes
+
+- `new_seq` field in `/effects` is now a String [#1604](https://github.com/stellar/go/pull/1604).
```
Comment (bartekn) [inline services/horizon/CHANGELOG.md]: Let's move it to the top.

File: protocols/horizon/effects/main.go [hunk 3]
```diff
@@ -198,7 +198,7 @@ type AccountFlagsUpdated struct {
 
 type SequenceBumped struct {
 	Base
-	NewSeq int64 `json:"new_seq"`
+	NewSeq string `json:"new_seq"`
```
Comment (bartekn) [inline protocols/horizon/effects/main.go]: I think we should use `string` tag:
> The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. This extra level of encoding is sometimes used when communicating with JavaScript programs:
> ```
> Int64String int64 `json:",string"`
> ```

So Go developers don't have to convert it back to `int64`.

Check [`Marshal`](https://golang.org/pkg/encoding/json/#Marshal) docs.

File: services/horizon/internal/db2/history/main.go (hunk 1 above)
Comment (bartekn) [reply services/horizon/internal/db2/history/main.go]: Looks good but `json` tag is not necessary here.

Comment (abuiles) [reply services/horizon/internal/db2/history/main.go]: @bartekn I removed it and the test failed since it couldn't parse the JSONB in String details -- under the hood we use `json.Unmarshal`  -- if we don't use the `json` tag, it would be looking for `NewSeq` not `new_seq`.

https://github.com/stellar/go/blob/6d635c3d1688bcb881ba49363c6ec92efd8f17ad/services/horizon/internal/db2/history/effect.go#L21

Comment (bartekn) [reply services/horizon/internal/db2/history/main.go]: Oh, you're right!

File: services/horizon/CHANGELOG.md (hunk 2 above)
Comment (abuiles) [reply services/horizon/CHANGELOG.md]: done

File: protocols/horizon/effects/main.go (hunk 3 above)
Comment (abuiles) [reply protocols/horizon/effects/main.go]: @bartekn done via https://github.com/stellar/go/commit/a9688dd7311c8c70ea5e15bb821f2f6b880202a6

I put an extra regression test to make sure that we never change the payload by mistake back to int64.

**Comment by abuiles** [comment]
@bartekn I addressed your comments, thanks!
