### PR TITLE
horizonclient: fix FetchTimebounds test

### LINKED ISSUE #1322: horizonclient: update tests for FetchTimebounds
Currently the tests are run against the public network. These should be mocked instead

### LINKED ISSUE #1323: support/http/httptest: add headers to response
Mocked responses should have the ability to have custom headers. Currently, only the response body can be mocked.

### PR DESCRIPTION
**Pull request by poliha**
This PR updates the tests for FetchTimebounds from sending requests to pubnet horizon server to mocking the horizon server responses. Prior to this, we were unable to mock this response because we could not return headers with the response. 
This PR also updates the `support/httptest` package to allow users mock responses with headers.

Closes #1322 
Closes #1323

### CODE REVIEW

File: clients/horizonclient/main_test.go [hunk 1]
```diff
@@ -1019,18 +1019,43 @@ func TestOrderBookRequest(t *testing.T) {
...
+		HTTP:       hmock,
+	}
 
+	// When no saved server time, return local time
 	st, err := client.FetchTimebounds(100)
 	if assert.NoError(t, err) {
-		assert.IsType(t, ServerTimeMap["horizon.stellar.org"], ServerTimeRecord{})
+		assert.IsType(t, ServerTimeMap["localhost"], ServerTimeRecord{})
+		assert.Equal(t, st.MinTime, int64(0))
+		// assert.Equal(t, st.MaxTime, int64(0))
```
Comment (ire-and-curses) [inline clients/horizonclient/main_test.go]: Can remove this commented out code
