### PR TITLE
Fix graceful shutdown

### LINKED ISSUE #777: Silent "database is closed" errors during shutdown
During shutdown a lot of errors like: `get failed: sql: database is closed` are generated that make alerts triggered. They should be either silenced or temporarily degraded to `WARN` level.

### PR DESCRIPTION
**Pull request by bartekn**
This commit fixes two issues connected to graceful shutdown in Horizon. First, application context was not correctly handled in actions. Because of this, streaming connections were not closed gracefully.

Streaming body during shutdown before the change:

```
retry: 1000
event: open
data: "hello"

curl: (18) transfer closed with outstanding read data remaining
```

Streaming body during shutdown after the change:

```
retry: 1000
event: open
data: "hello"

retry: 10
event: close
data: "byebye"
```

Second, DB connections were closed before requests handling was finished. This caused generation of `ERROR`-level log entries like `sql: database is closed` during shutdown. This commit runs the code that closes DB connections after the requests are properly closed.

Close #777.

### CODE REVIEW

File: services/horizon/internal/app.go [hunk 1]
```diff
@@ -110,16 +110,16 @@ func (a *App) Serve() {
 		log.Panic(err)
 	}
 
+	a.historyQ.Session.DB.Close()
+	a.coreQ.Session.DB.Close()
+
 	log.Info("stopped")
 }
 
 // Close cancels the app and forces the closure of db connections
```
Comment (howardtw) [inline services/horizon/internal/app.go]: We might need to update the comments here as well

File: services/horizon/internal/action.go [hunk 2]
```diff
@@ -54,7 +54,7 @@ func (action *Action) HistoryQ() *history.Q {
 func (action *Action) Prepare(w http.ResponseWriter, r *http.Request) {
 	base := &action.Base
 	action.App = AppFromContext(r.Context())
-	base.Prepare(w, r, action.App.config.SSEUpdateFrequency)
+	base.Prepare(w, r, action.App.ctx, action.App.config.SSEUpdateFrequency)
```
Comment (howardtw) [inline services/horizon/internal/action.go]: Can you explain the difference between the application context and the request context? Looking at line 56, it seems like the application context is derived from the request context.

File: services/horizon/internal/app.go (hunk 1 above)
Comment (bartekn) [reply services/horizon/internal/app.go]: Good point, actually created a new `App.CloseDB()` method that closes DB connections.

File: services/horizon/internal/action.go (hunk 2 above)
Comment (bartekn) [reply services/horizon/internal/action.go]: > Can you explain the difference between the application context and the request context?

Context on request is standard `net/http`: [`Request.Context()`](https://golang.org/pkg/net/http/#Request.Context), so it's cancelled "when the client's connection closes, the request is canceled (with HTTP/2), or when the ServeHTTP method returns.".

Application context is cancelled when application is shutting down (when `App.Close()` is called).

> Looking at line 56, it seems like the application context is derived from the request context.

Application object is added to context for quick access to application instance, ex. in action code. So if you ever need `App` object, you can just call `AppFromContext(r.Context())`.

File: services/horizon/internal/app.go [hunk 3]
```diff
@@ -110,14 +110,19 @@ func (a *App) Serve() {
 		log.Panic(err)
 	}
```
Comment (howardtw) [inline services/horizon/internal/app.go]: Can you add a comment here saying something like `Closes DB connections after the requests are properly closed to avoid "sql: database is closed" error during shutdown`?

Comment (bartekn) [reply services/horizon/internal/app.go]: Good point, extended the comment.
