### PR TITLE
AllowOverInt64 in amount.IntStringToAmount

### LINKED ISSUE #606: /assets numAccounts & amount incorrect
Check out what Horizon is reporting about `XIM` here: https://www.stellar.org/laboratory/#explorer?resource=assets&endpoint=single&values=eyJhc3NldF9jb2RlIjoiWElNIn0%3D&network=public

Currently, it shows the following:

- issuer: GBZ35ZJRIKJGYH5PBKLKOZ5L6EXCNTO7BKIL7DAVVDFQ2ODJEEHHJXIM
- numAccounts: 0
- amount: ""

Despite the fact that I and many others hold XIM.

Stellar.expert shows the real story: 
https://stellar.expert/explorer/public/asset/XIM-GBZ35ZJRIKJGYH5PBKLKOZ5L6EXCNTO7BKIL7DAVVDFQ2ODJEEHHJXIM

- numAccounts: 429
- amount: 10,000,000,000,000

Perhaps it's an issue with the 10T amount exceeding some check in Horizon?
@bartekn

### PR DESCRIPTION
**Pull request by bartekn**
This change allows parsing string integers larger than `int64` in `amount.IntStringToAmount`. This function is used in `/assets` endpoint and currently does not work for larger amounts. The bug was introduced in https://github.com/stellar/go/commit/5bf53ca1550b70f00e6294589d4fcb2497264b31.

This also adds error check in `AssetsAction.loadPage` (that's why it hasn't been caught earler).

Close #606.

### CODE REVIEW

File: amount/main.go [hunk 1]
```diff
@@ -84,8 +90,22 @@ func ParseInt64(v string) (int64, error) {
...
+func IntStringToAmount(v string, opts ...Option) (string, error) {
+	allowOverInt64 := false
+	for _, opt := range opts {
+		switch opt {
+		case AllowOverInt64:
+			allowOverInt64 = true
+		}
+	}
+
+	if !allowOverInt64 && !validAmountSimple.MatchString(v) {
```
Comment (nikhilsaraf) [inline amount/main.go]: @bartekn where in the code do we _fix_ the bug that causes the error?

my understanding is that now we will correctly catch and throw the error, but the error still exists.
I did see the new test and may have missed the part of the PR that fixes it so want to make sure it's there.

Comment (bartekn) [reply amount/main.go]: The actual fix is here: https://github.com/stellar/go/pull/609/files#diff-981180cdf0abda8125a97a2d79bcb503L24

https://github.com/stellar/go/commit/5bf53ca1550b70f00e6294589d4fcb2497264b31 was a result of a security report submitted to SDF's Bug Bounty program. I changed the `amount` package to return an error if the amount passed as an argument is too large. This was a security fix because passing a parameter to `/paths` like: `/paths?destination_amount=1E9223372036854775807` could basically DoS Horizon. I didn't realize (and also we don't have tests that cover this) that `amount.IntStringToAmount` function is used in `/assets` and sum of balances of an asset can be larger than `int64`. The line I linked above was basically failing silently without copying the rest of fields from DB result object. The change was to allow values larger that `int64` in `amount.IntStringToAmount` by passing an option: `AllowOverInt64`.

`amount.IntStringToAmount` function can be changed to remove `big.Rat` dependency (simple string algorithm). I'm planning to do it tomorrow and deploy patch releases (0.13.3 and 0.14.0rc3).

Comment (nikhilsaraf) [reply amount/main.go]: ok I see, makes sense. thanks!

**Comment by bartekn** [comment]
`amount.IntStringToAmount` is now using a much faster string algorithm.
