### PR TITLE
Fix server shutdown race

### LINKED ISSUE #2957: Data race in services/horizon/internal/httpx.(*Server).Shutdown
### What version are you using?

1.8.0 RC but looks like it can be an issue introduced in 1.7.0.

### What did you do?

Shutdown Horizon compiled with `-race`

### What did you expect to see?

No data races.

### What did you see instead?

```
WARNING: DATA RACE
Read at 0x00c00000e6d0 by goroutine 78:
  github.com/stellar/go/services/horizon/internal/httpx.(*Server).Shutdown()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/httpx/server.go:117 +0xd6
  github.com/stellar/go/services/horizon/internal.(*App).waitForDone()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/app.go:156 +0x130

Previous write at 0x00c00000e6d0 by goroutine 80:
  github.com/stellar/go/services/horizon/internal/httpx.(*Server).Serve.func1()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/httpx/server.go:87 +0x2a9

Goroutine 78 (running) created at:
  github.com/stellar/go/services/horizon/internal.(*App).Serve()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/app.go:134 +0x3c2
  github.com/stellar/go/services/horizon/cmd.glob..func10()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:37 +0x34
  github.com/stellar/go/services/horizon/internal.NewApp()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/app.go:96 +0x1f2
  github.com/stellar/go/services/horizon/cmd.initApp()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:390 +0xfd
  github.com/stellar/go/services/horizon/cmd.initRootConfig()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:407 +0xd1
  github.com/stellar/go/services/horizon/cmd.initApp()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:380 +0x47
  github.com/stellar/go/services/horizon/cmd.glob..func10()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:37 +0x2f
  github.com/spf13/cobra.(*Command).execute()
      /Users/Bartek/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:603 +0x7b8
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/Bartek/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:689 +0x36a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/Bartek/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:648 +0x4e
  github.com/stellar/go/services/horizon/cmd.Execute()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:446 +0x2f
  main.main()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/main.go:6 +0x2f

Goroutine 80 (running) created at:
  github.com/stellar/go/services/horizon/internal/httpx.(*Server).Serve()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/httpx/server.go:84 +0x3a4
  github.com/stellar/go/services/horizon/internal.(*App).Serve()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/app.go:136 +0x4e4
  github.com/stellar/go/services/horizon/cmd.glob..func10()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:37 +0x34
  github.com/stellar/go/services/horizon/internal.NewApp()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/internal/app.go:96 +0x1f2
  github.com/stellar/go/services/horizon/cmd.initApp()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:390 +0xfd
  github.com/stellar/go/services/horizon/cmd.initRootConfig()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:407 +0xd1
  github.com/stellar/go/services/horizon/cmd.initApp()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:380 +0x47
  github.com/stellar/go/services/horizon/cmd.glob..func10()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:37 +0x2f
  github.com/spf13/cobra.(*Command).execute()
      /Users/Bartek/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:603 +0x7b8
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/Bartek/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:689 +0x36a
  github.com/spf13/cobra.(*Command).Execute()
      /Users/Bartek/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:648 +0x4e
  github.com/stellar/go/services/horizon/cmd.Execute()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/cmd/root.go:446 +0x2f
  main.main()
      /Users/Bartek/go/src/github.com/stellar/go/services/horizon/main.go:6 +0x2f
==================
```

### PR DESCRIPTION
**Pull request by 2opremio**
Instead of using locks I simply initialize the servers during creation.
In that way there are no writes while serving.

Fixes #2957

### CODE REVIEW

**Comment by bartekn** [comment]
It fails with:
```
FATA[2020-08-27T15:50:59.331+02:00] server already started                        pid=32074
```
possibly because of:
```go
	if s.server != nil {
		return errors.New("server already started")
	}
```

**Comment by 2opremio** [comment]
@bartekn it should be good to go.

File: services/horizon/internal/httpx/server.go [hunk 1]
```diff
@@ -27,10 +27,14 @@ type ServerMetrics struct {
...
-	Metrics        *ServerMetrics
-	server         *http.Server
+	Router   *Router
+	Metrics  *ServerMetrics
+	server   *http.Server
+	tlsFiles *struct {
+		certFile, keyFile string
+	}
 	internalServer *http.Server
+	sync.RWMutex
```
Comment (bartekn) [inline services/horizon/internal/httpx/server.go:37]: Not used?
```suggestion
```

File: services/horizon/internal/app.go [hunk 2]
```diff
@@ -466,7 +466,8 @@ func (a *App) init() error {
 	}
 
 	var err error
-	a.webServer, err = httpx.NewServer(webConfig)
+	a.webServer, err = httpx.NewServer(
+		webConfig, uint16(a.config.Port), a.config.TLSCert, a.config.TLSKey, uint16(a.config.AdminPort))
```
Comment (bartekn) [inline services/horizon/internal/app.go:470]: Nit: Can we move the params to `httpx.RouterConfig` or a new `httpx.ServerConfig`? It's easy to mix params (ex. port with admin port).

**Review by bartekn — APPROVED** [review]
