### PR TITLE
services/horizon: Fix operations participants logic to include InvokeHostFunction operation

### LINKED ISSUE #5538: services/horizon: account operations endpoint does not include all operations affecting the account
### What version are you using?

`22.0.1-dd8a9b473a303cfcdd383d1db45dace93ea0861c`

### What did you do?

Go to:

https://horizon.stellar.org/accounts/GDZAGXA74ZE2B54TYUXNUAOY3MTDL3ECP4EPYTRO3TKKKBRZF265UERA/operations?order=desc

Go to:

https://horizon.stellar.org/accounts/GDZAGXA74ZE2B54TYUXNUAOY3MTDL3ECP4EPYTRO3TKKKBRZF265UERA/effects?order=desc

### What did you expect to see?

I expected to see present an operation and effects relating to:

https://horizon.stellar.org/operations/234143333304045569

The operation affects the GDZA account because a transfer is made to the account during the operation.

I expected this because the account operations endpoint shows payments from other source accounts that affect the GDZA account.

### What did you see instead?

The operation is seen in the /effects endpoint, but not the /operations endpoint.

---

Related conversion: https://stellarfoundation.slack.com/archives/C03347FNAHK/p1732298224113449

cc @tomerweller

### PR DESCRIPTION
**Pull request by urvisavla**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've reviewed the changes in this PR and if I consider them worthwhile for being mentioned on release notes then I have updated the relevant `CHANGELOG.md` within the  component folder structure. For example, if I changed horizon, then I updated ([services/horizon/CHANGELOG.md](services/horizon/CHANGELOG.md). I add a new line item describing the change and reference to this PR. If I don't update a CHANGELOG, I acknowledge this PR's change may not be mentioned in future release notes.  
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What
Updates participant detection logic for the InvokeHostFunction operation type. When a smart contract is invoked, the accounts affected will be identified by iterating through the events. Additionally, the logic examines the list of changes resulting from the operation to ensure all affected accounts are detected.

All SAC integration tests have been updated to verify that the accounts/<>/operations endpoint correctly returns the InvokeHostFunction operation for the affected accounts.

### Why

Fixes #5538 

### Known limitations
- Currently, only burn, mint, clawback and transfer events processed to determine affected accounts since Horizon recognizes only those events.
- Ingestion filtering based on assets and accounts does not currently handle those affected by invoking smart contract. This should be addressed as a separate scope of work.

### CODE REVIEW

File: services/horizon/internal/ingest/processors/operations_processor.go [hunk 1]
```diff
@@ -1047,7 +1047,68 @@ func (operation *transactionOperationWrapper) Participants() ([]xdr.AccountId, e
...
+		if err != nil {
+			return participants, err
+		}
+
+		for _, contractEvent := range filterEvents(diagnosticEvents) {
+			if sacEvent, err := contractevents.NewStellarAssetContractEvent(&contractEvent, operation.network); err == nil {
+				switch sacEvent.GetType() {
+				case contractevents.EventTypeTransfer:
+					transferEvt := sacEvent.(*contractevents.TransferEvent)
+					if from, err := xdr.AddressToAccountId(transferEvt.From); err == nil {
```
Comment (Shaptic) [inline services/horizon/internal/ingest/processors/operations_processor.go:1087]: Is the intent here to skip contract addresses as participants?

Comment (urvisavla) [reply services/horizon/internal/ingest/processors/operations_processor.go:1087]: Yes.

Comment (urvisavla) [reply services/horizon/internal/ingest/processors/operations_processor.go:1062]: added comment to clarify the intent.

File: services/horizon/internal/ingest/processors/operations_processor.go [hunk 2]
```diff
@@ -1047,7 +1047,74 @@ func (operation *transactionOperationWrapper) Participants() ([]xdr.AccountId, e
...
+					case xdr.LedgerEntryTypeAccount:
+						participants = append(participants, data.MustAccount().AccountId)
+					case xdr.LedgerEntryTypeTrustline:
+						participants = append(participants, data.MustTrustLine().AccountId)
+					}
+				}
+			}
+		}
+
+		if diagnosticEvents, err := operation.transaction.GetDiagnosticEvents(); err != nil {
```
Comment (urvisavla) [inline services/horizon/internal/ingest/processors/operations_processor.go:1076]: Events are recorded at the transaction level but when using InvokeHostFunction operation, there is only one operation per transaction. This makes it ok to evaluate events in the context of operation. However, if there were multiple such operations in a transaction, the events would need to include an identifier for the operation id.

File: services/horizon/internal/ingest/processors/operations_processor.go [hunk 3]
```diff
@@ -1099,6 +1166,7 @@ func operationsParticipants(transaction ingest.LedgerTransaction, sequence uint3
 			transaction:    transaction,
 			operation:      op,
 			ledgerSequence: sequence,
+			network:        network,
```
Comment (urvisavla) [inline services/horizon/internal/ingest/processors/operations_processor.go:1169]: Is there a way to get the network passphrase directly from the transaction instead of passing it?

File: services/horizon/internal/ingest/processors/operations_processor.go [hunk 4]
```diff
@@ -1047,7 +1047,74 @@ func (operation *transactionOperationWrapper) Participants() ([]xdr.AccountId, e
...
+						continue
+					}
+
+					switch change.Type {
+					case xdr.LedgerEntryTypeAccount:
+						participants = append(participants, data.MustAccount().AccountId)
+					case xdr.LedgerEntryTypeTrustline:
+						participants = append(participants, data.MustTrustLine().AccountId)
+					}
+				}
```
Comment (tamirms) [inline services/horizon/internal/ingest/processors/operations_processor.go:1072]: there is a helper function in this file `getLedgerKeyParticipants()` which can be used to extract relevant accounts from ledger entries

File: services/horizon/internal/ingest/processors/operations_processor.go (hunk 2 above)
Comment (tamirms) [inline services/horizon/internal/ingest/processors/operations_processor.go:1076]: I think the code to extract participants from contract events should be refactored into a helper function

File: services/horizon/internal/ingest/processors/operations_processor.go (hunk 3 above)
Comment (tamirms) [reply services/horizon/internal/ingest/processors/operations_processor.go:1169]: unfortunately not

File: services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go [hunk 5]
```diff
@@ -2285,3 +2289,110 @@ func TestDetailsCoversAllOperationTypes(t *testing.T) {
...
+
+	transferContractEvent := contractevents.GenerateEvent(contractevents.EventTypeTransfer, transferEvtFromAcc, transferEvtToAcc, "", randomAsset, big.NewInt(10000000), passphrase)
+	mintContractEvent := contractevents.GenerateEvent(contractevents.EventTypeMint, "", mintEvtAcc, randomAccount, randomAsset, big.NewInt(10000000), passphrase)
+	burnContractEvent := contractevents.GenerateEvent(contractevents.EventTypeBurn, burnEvtAcc, "", randomAccount, randomAsset, big.NewInt(10000000), passphrase)
+	clawbackContractEvent := contractevents.GenerateEvent(contractevents.EventTypeClawback, clawbkEvtAcc, "", randomAccount, randomAsset, big.NewInt(10000000), passphrase)
+
+	tx1 := ingest.LedgerTransaction{
+		UnsafeMeta: xdr.TransactionMeta{
+			V: 3,
+			V3: &xdr.TransactionMetaV3{
```
Comment (Shaptic) [inline services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go:2316]: This is going to be a pain to generate for V3 _and_ V4 once that comes out but :shrug: that's the burden we'll have to bear

File: services/horizon/internal/integration/sac_test.go [hunk 6]
```diff
@@ -1164,6 +1170,23 @@ func getTxEffects(itest *integration.Test, txHash string, asset xdr.Asset) []eff
 	return result
 }
 
+func assertAccountInvokeHostFunctionOperation(itest *integration.Test, account string, from string, to string, amount string) {
```
Comment (Shaptic) [inline services/horizon/internal/integration/sac_test.go:1173]: really nice coverage :clap:

File: services/horizon/internal/ingest/processors/operations_processor.go (hunk 4 above)
Comment (urvisavla) [reply services/horizon/internal/ingest/processors/operations_processor.go]: done

File: services/horizon/internal/ingest/processors/operations_processor.go (hunk 2 above)
Comment (urvisavla) [reply services/horizon/internal/ingest/processors/operations_processor.go:1069]: done.

**Review by tamirms — APPROVED** [review]
