### PR TITLE
exp/ingest/pipeline: Fix pipeline data race during shutdown

### LINKED ISSUE #2046: services/horizon: Data race during expingest shutdown
### What version are you using?

Horizon 0.24.0 RC

### What did you do?

1. Run Horizon with race detector (`-race`).
2. Send `SIGTERM` signal.

### What did you expect to see?

No data races.

### What did you see instead?

First occurrence:
```
INFO[2019-12-11T15:29:52.344+01:00] Reading new ledger                            ledger=27212116 pid=1997 service=expingest
INFO[2019-12-11T15:29:52.345+01:00] Processing ledger                             ledger=27212116 pid=1997 service=expingest type=ledger_pipeline updating_database=true
INFO[2019-12-11T15:29:55.556+01:00] Processed ledger                              ledger=27212116 pid=1997 service=expingest type=ledger_pipeline
INFO[2019-12-11T15:29:55.557+01:00] Finished processing ledger                    duration=3.212663749 ledger=27212116 pid=1997 service=expingest transactions=54
^CINFO[2019-12-11T15:29:56.283+01:00] received signal, gracefully stopping          pid=1997
INFO[2019-12-11T15:29:56.283+01:00] Shutting down ingestion system...             pid=1997 service=expingest
INFO[2019-12-11T15:29:57.267+01:00] finished background ticker                    pid=1997
INFO[2019-12-11T15:29:57.352+01:00] Reading new ledger                            ledger=27212117 pid=1997 service=expingest
INFO[2019-12-11T15:29:57.354+01:00] Processing ledger                             ledger=27212117 pid=1997 service=expingest type=ledger_pipeline updating_database=true
INFO[2019-12-11T15:29:57.355+01:00] Processing ledger shutdown                    duration=0.002914144 ledger=27212117 pid=1997 service=expingest
INFO[2019-12-11T15:29:57.356+01:00] Session shut down                             pid=1997 service=expingest
INFO[2019-12-11T15:29:57.358+01:00] stopped                                       pid=1997
WARNING: DATA RACE
Read at 0x00c0003996f8 by goroutine 87:
  github.com/stellar/go/support/db.(*Session).ExecRaw()
      /Users/bartek/gocode/src/github.com/stellar/go/support/db/session.go:362 +0xe1
  github.com/stellar/go/support/db.(*Session).Exec()
      /Users/bartek/gocode/src/github.com/stellar/go/support/db/session.go:170 +0x100
  github.com/stellar/go/services/horizon/internal/db2/history.(*Q).UpdateAccount()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/db2/history/accounts.go:108 +0x38f
  github.com/stellar/go/services/horizon/internal/expingest/processors.(*DatabaseProcessor).processLedgerAccounts()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/processors/database_processor.go:490 +0x2e9
  github.com/stellar/go/services/horizon/internal/expingest/processors.(*DatabaseProcessor).processLedgerAccounts-fm()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/processors/database_processor.go:454 +0x61
  github.com/stellar/go/services/horizon/internal/expingest/processors.(*DatabaseProcessor).ProcessLedger()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/processors/database_processor.go:244 +0x91a
  github.com/stellar/go/exp/ingest/pipeline.(*ledgerProcessorWrapper).Process()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/ingest/pipeline/wrappers.go:24 +0x280
  github.com/stellar/go/exp/support/pipeline.(*Pipeline).processStateNode.func1()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/support/pipeline/pipeline.go:177 +0x10b

Previous write at 0x00c0003996f8 by goroutine 54:
  github.com/stellar/go/support/db.(*Session).Rollback()
      /Users/bartek/gocode/src/github.com/stellar/go/support/db/session.go:285 +0xc4
  github.com/stellar/go/services/horizon/internal/db2/history.(*Q).Rollback()
      <autogenerated>:1 +0x5d
  github.com/stellar/go/services/horizon/internal/expingest.(*System).Run.func2()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/main.go:310 +0x374
  github.com/stellar/go/services/horizon/internal/expingest.alwaysRetry.onError()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/main.go:119 +0x86
  github.com/stellar/go/services/horizon/internal/expingest.(*alwaysRetry).onError()
      <autogenerated>:1 +0x66
  github.com/stellar/go/services/horizon/internal/expingest.(*System).Run()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/main.go:233 +0x14f
  github.com/stellar/go/services/horizon/internal.(*App).Serve.func2()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/app.go:109 +0x56

Goroutine 87 (running) created at:
  github.com/stellar/go/exp/support/pipeline.(*Pipeline).processStateNode()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/support/pipeline/pipeline.go:174 +0x43f
  github.com/stellar/go/exp/support/pipeline.(*Pipeline).processStateNode.func2()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/support/pipeline/pipeline.go:201 +0x12c

Goroutine 54 (finished) created at:
  github.com/stellar/go/services/horizon/internal.(*App).Serve()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/app.go:108 +0x75b
  github.com/stellar/go/services/horizon/cmd.glob..func11()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/cmd/root.go:31 +0x34
  github.com/spf13/cobra.(*Command).execute()
      /Users/bartek/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:603 +0x7b8
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bartek/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:689 +0x36a
  github.com/stellar/go/services/horizon/cmd.Execute()
      /Users/bartek/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:648 +0x4e
  main.main()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/main.go:6 +0x2f
==================
Found 1 data race(s)
```
Second occurrence:
```
==================
WARNING: DATA RACE
Read at 0x00c00016fa58 by goroutine 36:
  github.com/stellar/go/support/db.(*Session).ExecRaw()
      /Users/bartek/gocode/src/github.com/stellar/go/support/db/session.go:362 +0xe1
  github.com/stellar/go/support/db.(*Session).Exec()
      /Users/bartek/gocode/src/github.com/stellar/go/support/db/session.go:170 +0x100
  github.com/stellar/go/services/horizon/internal/db2/history.(*Q).UpdateTrustLine()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/db2/history/trust_lines.go:89 +0x400
  github.com/stellar/go/services/horizon/internal/expingest/processors.(*DatabaseProcessor).processLedgerTrustLines()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/processors/database_processor.go:765 +0x40b
  github.com/stellar/go/services/horizon/internal/expingest/processors.(*DatabaseProcessor).processLedgerTrustLines-fm()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/processors/database_processor.go:715 +0x61
  github.com/stellar/go/services/horizon/internal/expingest/processors.(*DatabaseProcessor).ProcessLedger()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/processors/database_processor.go:246 +0x91a
  github.com/stellar/go/exp/ingest/pipeline.(*ledgerProcessorWrapper).Process()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/ingest/pipeline/wrappers.go:24 +0x280
  github.com/stellar/go/exp/support/pipeline.(*Pipeline).processStateNode.func1()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/support/pipeline/pipeline.go:177 +0x10b

Previous write at 0x00c00016fa58 by goroutine 54:
  github.com/stellar/go/support/db.(*Session).Rollback()
      /Users/bartek/gocode/src/github.com/stellar/go/support/db/session.go:285 +0xc4
  github.com/stellar/go/services/horizon/internal/db2/history.(*Q).Rollback()
      <autogenerated>:1 +0x5d
  github.com/stellar/go/services/horizon/internal/expingest.(*System).Run.func2()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/main.go:311 +0x3e2
  github.com/stellar/go/services/horizon/internal/expingest.alwaysRetry.onError()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/main.go:119 +0x86
  github.com/stellar/go/services/horizon/internal/expingest.(*alwaysRetry).onError()
      <autogenerated>:1 +0x66
  github.com/stellar/go/services/horizon/internal/expingest.(*System).Run()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/expingest/main.go:233 +0x14f
  github.com/stellar/go/services/horizon/internal.(*App).Serve.func2()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/app.go:109 +0x56

Goroutine 36 (running) created at:
  github.com/stellar/go/exp/support/pipeline.(*Pipeline).processStateNode()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/support/pipeline/pipeline.go:174 +0x43f
  github.com/stellar/go/exp/support/pipeline.(*Pipeline).processStateNode.func2()
      /Users/bartek/gocode/src/github.com/stellar/go/exp/support/pipeline/pipeline.go:201 +0x12c

INFO[2019-12-11T16:04:40.724+01:00] stopped                                       pid=5074
Goroutine 54 (finished) created at:
  github.com/stellar/go/services/horizon/internal.(*App).Serve()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/internal/app.go:108 +0x75b
  github.com/stellar/go/services/horizon/cmd.glob..func11()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/cmd/root.go:31 +0x34
  github.com/spf13/cobra.(*Command).execute()
      /Users/bartek/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:603 +0x7b8
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/bartek/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:689 +0x36a
  github.com/stellar/go/services/horizon/cmd.Execute()
      /Users/bartek/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20160830174925-9c28e4bbd74e/command.go:648 +0x4e
  main.main()
      /Users/bartek/gocode/src/github.com/stellar/go/services/horizon/main.go:6 +0x2f
==================
Found 1 data race(s)
```

### PR DESCRIPTION
**Pull request by bartekn**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [x] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

This commit fixes data race in `exp/ingest/pipeline` that can occur when `LiveSession` (and Horizon) is shut down.

It also removes `updateStats` method that was known to have a data race (see comment in that method). It is not actively used right now but was being reported by race detector.

Fix #2046.

### Why

Previous code handling shutdown signal in `LiveSession` can be found below:
https://github.com/stellar/go/blob/5e4d247fd1d8e1f6a8ff364de0954de07d0fd6b7/exp/ingest/live_session.go#L196-L217

The problem is when shutdown signal is received, `Resume` returns `nil` so Horizon starts it's shutdown code which calls `Rollback()` (using internal `tx` object) but at the same time pipeline is still running until the code receiving from `ctx.Done` channel is executed. It means that pipeline processors can execute transactions using `tx` transaction object in DB session. See #2046 for examples.

To fix this:
1. We don't `select` ingest session shutdown signal when waiting for pipeline to finish processing.
2. Instead we call `Shutdown` on pipelines inside `LiveSession.Shutdown`.
3. Then we wait/block until pipelines gracefully shutdown by calling `Pipeline.IsRunning` method.
4. Finally we `close(s.shutdown)` inside `expingest/System.Shutdown()`.

So the components now shut down exactly in the following order:
1. Pipelines.
2. Session.
3. Horizon Expingest System.

One comment on `-1` change in tests. When `ingestSession.Run()` returns `nil` we shouldn't continue to `ingestSession.Resume()` because `nil` value means that session ended. I updated the comment in `LiveSession` and also fixed Horizon code.

### Known limitations

Pipeline design is very powerful but it's also very easy to introduce data races like this one. We may want to refactor this as noted previously in #2050.

### CODE REVIEW

File: exp/ingest/live_session.go [hunk 1]
```diff
@@ -107,6 +110,14 @@ func (s *LiveSession) updateCursor(ledgerSequence uint32) error {
 func (s *LiveSession) Resume(ledgerSequence uint32) error {
 	s.standardSession.shutdown = make(chan bool)
 
+	err := s.validate()
```
Comment (abuiles) [inline exp/ingest/live_session.go]: @bartekn did we forget to add this before?

Comment (bartekn) [reply exp/ingest/live_session.go]: Yes, there are two _entry points_ to `LiveSession`: `Run` or `Resume`.
