### PR TITLE
services/horizon: Gracefully handle incorrect assets in `GET /offers`

### LINKED ISSUE #2466: services/horizon: Handle bad request to offers, don't throw a 500
The following request causes a 500 

`/offers?buying=native\\u0026cursor=\\u0026limit=10\\u0026order=asc\\u0026selling=BTC%3AGAEDZ7BHMDYEMU6IJT3CTTGDUSLZWS5CQWZHGP4XUOIDG5ISH3AFAEK2`

### PR DESCRIPTION
**Pull request by 2opremio**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Fixes #2466 

Gracefully handle incorrect assets in the query parameters of `GET /offers`.

Before this change, a panic happened and a ` 500` HTTP error was returned.

### Why

A `500` is incorrect and not helpful for the end user.

### Known limitations

N/A

### CODE REVIEW

File: services/horizon/internal/actions/offer.go [hunk 1]
```diff
@@ -90,11 +92,24 @@ func (handler GetOffersHandler) GetResourcePage(
 		return nil, err
 	}
 
+	selling, err := qp.Selling()
+	if err != nil {
+		p := problem.BadRequest
```
Comment (abuiles) [inline services/horizon/internal/actions/offer.go:97]: we have a helper for this `problem.MakeInvalidFieldProblem`

File: services/horizon/internal/actions/offer.go [hunk 2]
```diff
@@ -90,11 +92,24 @@ func (handler GetOffersHandler) GetResourcePage(
...
+		p.Extras = map[string]interface{}{"reason": fmt.Sprintf("bad selling asset: %s", err.Error())}
+		return nil, p
+	}
+	buying, err := qp.Buying()
+	if err != nil {
+		p := problem.BadRequest
```
Comment (abuiles) [inline services/horizon/internal/actions/offer.go:103]: ditto

File: services/horizon/internal/actions/offer.go (hunk 1 above)
Comment (abuiles) [reply services/horizon/internal/actions/offer.go:97]: also, can we make `selling` return a `problem.MakeInvalidFieldProblem` so we don't have to do it here - also we can tell exactly which query param caused the error

Comment (2opremio) [reply services/horizon/internal/actions/offer.go:97]: You are partly right. I should had returned the error in `Selling()` and `Buying()` but if `xdr.BuildAsset` fails, you can't tell which parameter caused the problem.

**Comment by 2opremio** [comment]
@abuiles PTAL

**Comment by 2opremio** [comment]
> Also we should have caught that it was invalid in the custom validators for each part of the asset, that is `assetType` or `asset`

I would rather address this separately. But I will do it here if you think I should.

File: services/horizon/internal/actions/query_params.go [hunk 3]
```diff
@@ -79,29 +90,42 @@ func (q SellingBuyingAssetQueryParams) Selling() *xdr.Asset {
 	)
 
 	if err != nil {
-		panic(err)
+		p := problem.BadRequest
```
Comment (abuiles) [inline services/horizon/internal/actions/query_params.go:93]: we can use `problem.MakeInvalidFieldProblem` here too

File: services/horizon/internal/actions/query_params.go [hunk 4]
```diff
@@ -111,8 +135,10 @@ func (q SellingBuyingAssetQueryParams) Buying() *xdr.Asset {
...
```
Comment (abuiles) [inline services/horizon/internal/actions/query_params.go:138]: we can use `problem.MakeInvalidFieldProblem`

File: services/horizon/internal/actions/query_params.go (hunk 3 above)
Comment (2opremio) [reply services/horizon/internal/actions/query_params.go:93]: I don't think we can, because we don't know what field caused it.

Comment (abuiles) [reply services/horizon/internal/actions/query_params.go:93]: oh I see, because is one of the parts right? can we use  `selling`?

Comment (2opremio) [reply services/horizon/internal/actions/query_params.go:93]: I think it could be in the other parameters. Using `selling` could be misleading. I would rather leave it as is.

Comment (abuiles) [reply services/horizon/internal/actions/query_params.go:93]: sounds good!
