### PR TITLE
txnbuild: Fix manage data value in sep10 challenge

### LINKED ISSUE #1562: SEP 10 implementation of manage data value needs to be base64-encoded
As pointed out by SDK maintainer bnogal on keybase, SEP 10 spec says:

> operations: manage_data(source: client_account, key: '<anchor name> auth', value: random_nonce())

>    The value of key is not important, but can be the name of the anchor followed by auth. It can be at most 64 bytes.
    The value must be a 64 byte long base64 encoded cryptographic-quality random string

Our implementation [does not apply](https://github.com/stellar/go/blob/7cbe600be34a4bfffd3ce270f136c78aefffa241/txnbuild/transaction.go#L212) the base64 encoding to the random nonce. It should.

### PR DESCRIPTION
**Pull request by poliha**
This PR uses the correct length of bytes for the manage data value. 
As per the protocol
>The value must be 64 bytes long. It contains a 48 byte cryptographic-quality random string encoded using base64 (for a total of 64 bytes after encoding).

Closes #1562

### CODE REVIEW

File: txnbuild/transaction.go [hunk 1]
```diff
@@ -210,13 +210,13 @@ func BuildChallengeTx(serverSignerSecret, clientAccountID, anchorName, network s
 		return "", err
 	}
 
-	randomNonce, err := generateRandomNonce(64)
+	randomNonce, err := generateRandomNonce(48)
```
Comment (abuiles) [inline txnbuild/transaction.go]: You still need to convert this to base64 and then back to bytes for a total of 64 bytes. Otherwise turning the `randonNonce` to a string will return random characters, not necessarily ASCII.

File: txnbuild/transaction.go [hunk 2]
```diff
@@ -210,13 +210,13 @@ func BuildChallengeTx(serverSignerSecret, clientAccountID, anchorName, network s
...
 	if err != nil {
 		return "", err
 	}
 
-	if len(randomNonce) != 64 {
-		return "", errors.New("64 byte long random nonce required")
+	if len(randomNonce) != 48 {
```
Comment (abuiles) [inline txnbuild/transaction.go]: should still be 64.

File: txnbuild/transaction.go (hunk 1 above)
Comment (poliha) [reply txnbuild/transaction.go]: Hmmm I see your point, my assumption was that to turn the randomNonce to a string, the user will do 
```golang
v := base64.StdEncoding.EncodeToString(ManageDataOp.DataValue)
```
And Not
```golang
	v := string(ManageDataOp.DataValue)
```
But as we discussed, we are really just interested in the final value being 64bytes, so it makes sense to do the encoding before passing the value to the operation.

File: txnbuild/transaction_test.go [hunk 3]
```diff
@@ -754,7 +754,7 @@ func TestBuildChallengeTx(t *testing.T) {
 	op := txXDR.Tx.Operations[0]
 	assert.Equal(t, xdr.OperationTypeManageData, op.Body.Type, "operation type should be manage data")
 	assert.Equal(t, xdr.String64("SDF auth"), op.Body.ManageDataOp.DataName, "DataName should be 'SDF auth'")
-	assert.Equal(t, 64, len(*op.Body.ManageDataOp.DataValue), "DataValue should be 64 bytes")
+	assert.Equal(t, 64, len(*op.Body.ManageDataOp.DataValue), "DataValue should be 48 bytes")
```
Comment (abuiles) [inline txnbuild/transaction_test.go]: Typo: 64 bytes.

File: txnbuild/transaction.go [hunk 4]
```diff
@@ -210,12 +210,14 @@ func BuildChallengeTx(serverSignerSecret, clientAccountID, anchorName, network s
...
+	// SEP10 spec requires 48 byte cryptographic-quality random string
+	randomNonce, err := generateRandomNonce(48)
 	if err != nil {
 		return "", err
 	}
-
-	if len(randomNonce) != 64 {
+	// Encode 48-byte nonce to base64 for a total of 64-bytes
+	randomNonceToString := base64.StdEncoding.EncodeToString(randomNonce)
+	if len(randomNonceToString) != 64 {
```
Comment (abuiles) [inline txnbuild/transaction.go]: NIT: I don't think we need this check here -- we already have an unit test.
