### PR TITLE
txnbuild: add max limit to change trust

### LINKED ISSUE #1265: txnbuild: default to max limit for trustlines
At the moment, attempting to build a `txnbuild.ChangeTrust` operation without a trustline limit will fail with a low level parse error.

The JS  SDK [defaults](https://stellar.github.io/js-stellar-sdk/node_modules_stellar-base_src_operations_change_trust.js.html) to the max limit (`int64`) if no amount is specified. We should

- [ ] - add a `MaxTrustlineLimit` const
- [ ] - default to this value if no `Limit` is specified
- [ ] - document this behaviour in the GoDoc

### PR DESCRIPTION
**Pull request by poliha**
This PR adds the maximum trustline limit to a change trust operation when no limit is set. 
Closes #1265

### CODE REVIEW

File: txnbuild/change_trust.go [hunk 1]
```diff
@@ -1,19 +1,25 @@
...
-// https://www.stellar.org/developers/guides/concepts/list-of-operations.html
+// https://www.stellar.org/developers/guides/concepts/list-of-operations.html.
+// If Limit is omitted,  it defaults to txnbuild.MaxTrustlineLimit; the max int64 value.
 type ChangeTrust struct {
 	Line          Asset
 	Limit         string
 	SourceAccount Account
 }
 
+// MaxTrustlineLimit represents the maximum value that can be passed as trutline Limit
```
Comment (ire-and-curses) [inline txnbuild/change_trust.go]: `can be passed as trutline Limit` -> `can be set as a trustline limit.`

File: txnbuild/change_trust.go [hunk 2]
```diff
@@ -1,19 +1,25 @@
...
+
 	"github.com/stellar/go/amount"
 	"github.com/stellar/go/support/errors"
 	"github.com/stellar/go/xdr"
 )
 
 // ChangeTrust represents the Stellar change trust operation. See
-// https://www.stellar.org/developers/guides/concepts/list-of-operations.html
+// https://www.stellar.org/developers/guides/concepts/list-of-operations.html.
+// If Limit is omitted,  it defaults to txnbuild.MaxTrustlineLimit; the max int64 value.
```
Comment (ire-and-curses) [inline txnbuild/change_trust.go]: ` // If Limit is omitted,  it defaults to txnbuild.MaxTrustlineLimit; the max int64 value.` -> ` // If Limit is omitted, it defaults to txnbuild.MaxTrustlineLimit.`

File: txnbuild/change_trust.go [hunk 3]
```diff
@@ -1,19 +1,25 @@
...
 type ChangeTrust struct {
 	Line          Asset
 	Limit         string
 	SourceAccount Account
 }
 
+// MaxTrustlineLimit represents the maximum value that can be passed as trutline Limit
+var MaxTrustlineLimit = amount.StringFromInt64(math.MaxInt64)
```
Comment (ire-and-curses) [inline txnbuild/change_trust.go]: can this be a `const`?

File: txnbuild/change_trust_test.go [hunk 4]
```diff
@@ -0,0 +1,27 @@
+package txnbuild
+
+import (
+	"testing"
+
+	"github.com/stellar/go/network"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestChangeTrustMaxLimit(t *testing.T) {
```
Comment (ire-and-curses) [inline txnbuild/change_trust_test.go]: Did you confirm by looking e.g. in Stellar lab that the limit was set as expected in the XDR? If so this is fine - just include the link to the lab.

File: txnbuild/change_trust.go (hunk 3 above)
Comment (poliha) [reply txnbuild/change_trust.go]: Nope you will get an error because the value is returned from a method

File: txnbuild/change_trust_test.go (hunk 4 above)
Comment (poliha) [reply txnbuild/change_trust_test.go]: Yep.. will add link
