### PR TITLE
Misc fixes

### LINKED ISSUE #5350: ingest/ledgerbackend: Captive core's LogLineWriter should be closed synchronously
We just close the writer side of the pipe but don't wait for the goroutine to exit:

https://github.com/stellar/go/blob/a4e5a3fc6664f7cf6b26fb3196b366910563636f/ingest/ledgerbackend/stellar_core_runner.go#L197-L209

This can cause an extra log line to be written after closing the backend. Which causes problems in the new Soroban RPC integration tests. See https://github.com/stellar/soroban-rpc/actions/runs/9538438244/job/26287637351?pr=216#step:10:50

### LINKED ISSUE #5351: historyarchive: should not use default logger
For instance:

https://github.com/stellar/go/blob/a4e5a3fc6664f7cf6b26fb3196b366910563636f/historyarchive/archive_pool.go#L109-L114

Causes a log to happen without any control. A logger, controlled by the caller, should be used instead or no logging should happen.

For instance, this causes untrackable logs to happen in tests . e.g: https://github.com/stellar/soroban-rpc/actions/runs/9538438244/job/26287637351?pr=216#step:10:22

The log cannot be attributed to a particular test, which is problematic (and noisy)

### PR DESCRIPTION
**Pull request by 2opremio**
Closes #5351 
Closes #5350 (including the removal of a nasty cast)
Addresses part of #5349 

Remove redundant code of `(*Session) Begin()`

### CODE REVIEW

File: historyarchive/archive_pool.go [hunk 1]
```diff
@@ -107,8 +110,8 @@ func (pa *ArchivePool) runRoundRobin(runner func(ai ArchiveInterface) error) err
 		}
 
 		// Intentionally avoid logging context errors
-		if stats := ai.GetStats(); len(stats) > 0 {
-			log.WithField("error", err).Warnf(
+		if stats := ai.GetStats(); len(stats) > 0 && pa.logger != nil {
```
Comment (sreuland) [inline historyarchive/archive_pool.go:113]: for consider, short circuit on logger presence instead:
```
if pa.logger == nil {
    return err
}
```

Comment (2opremio) [reply historyarchive/archive_pool.go:113]: I didn't want to modify how the library behaved

File: ingest/ledgerbackend/main.go [hunk 2]
```diff
@@ -49,36 +48,39 @@ type cmdI interface {
...
+	getStdout() *logLineWriter
+	setStderr(stderr *logLineWriter)
+	getStderr() *logLineWriter
 	getProcess() *os.Process
 	setExtraFiles([]*os.File)
 }
 
 type realCmd struct {
 	*exec.Cmd
+	stdout, stderr *logLineWriter
```
Comment (sreuland) [inline ingest/ledgerbackend/main.go:61]: can this continue to use abstraction with an interface still rather direct struct ref, seems like it could get by with `io.PipeWriter`? and then instances of logLineWriter or mocks can be used by callers/tests.

**Review by sreuland — APPROVED** [review]
I left comment for consideration, using [interface vs struct for log line writer](https://github.com/stellar/go/pull/5352/files#r1643206851). your choice, otherwise, lgtm!

File: ingest/ledgerbackend/main.go (hunk 2 above)
Comment (2opremio) [reply ingest/ledgerbackend/main.go:61]: I considered it, but I didn’t see a need for it.

**Comment by 2opremio** [comment]
Unfortunately this didn't fully fix the logging race condition, we should fix https://github.com/stellar/go/issues/5342
