### PR TITLE
Fix tradeagg rebuild from reingest command with parallel workers

### LINKED ISSUE #5127: services/horizon/ingest: RebuildTradeAggregationBuckets cannot be invoked concurrently during parallel ingestion
### What version are you using?

build from latest on master

### What did you do?

Run parallel reingestion jobs, 

### What did you expect to see?

[RebuildTradeAggregationBuckets()](https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/fsm.go#L856) should work without error given parallel workers. 

### What did you see instead?

[RebuildTradeAggregationBuckets()](https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/fsm.go#L856) cannot be invoked concurrently during parallel ingestion because there will be duplicate key constraint errors when two workers invoke the function on adjacent buckets. That is because the buckets occur on minute boundaries and two adjacent ledger ranges will share the same trade aggregations bucket. 

This can potentially be fixed by modifying parallel reingestion so that the trade aggregation buckets are built once all the workers have completed their ingestion jobs.

related to #5099

### PR DESCRIPTION
**Pull request by sreuland**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

for reingest command, consolidate the invocations of rebuilding of trade agg buckets to once at end of all parallel workers

### Why

this avoids getting:
```
Error rebuilding trade aggregations: could not rebuild trade aggregation bucket: exec failed: pq: duplicate key value violates unique constraint \"history_trades_60000_pkey\

```
at the end of a parallel worker's range ingestion

Closes #5127 

### Known limitations

this is targeting the 2.28.0 release branch, it will be ported to master as part of porting the final release back to master later.

### CODE REVIEW

File: services/horizon/internal/ingest/main.go [hunk 1]
```diff
@@ -170,10 +170,11 @@ type System interface {
 	StressTest(numTransactions, changesPerTransaction int) error
 	VerifyRange(fromLedger, toLedger uint32, verifyState bool) error
 	BuildState(sequence uint32, skipChecks bool) error
-	ReingestRange(ledgerRanges []history.LedgerRange, force bool) error
+	ReingestRange(ledgerRanges []history.LedgerRange, force bool, rebuildTradAgg bool) error
```
Comment (urvisavla) [inline services/horizon/internal/ingest/main.go:173]:
```suggestion
	ReingestRange(ledgerRanges []history.LedgerRange, force bool, rebuildTradeAgg bool) error
```

**Review by urvisavla — APPROVED** [review]
Reingestion logic has some intricacies but the changes lgtm.
