### PR TITLE
fix paging

### LINKED ISSUE #148: Paging should respect query filters
Right now, `self`, `next` and `prev` links don't respect the query filters from the original query.

### PR DESCRIPTION
**Pull request by tomerweller**
apply query filters on paging links. closes #148 

also:
- modifies the Page struct to include a full url, rather than separate base url, path and query params. 
- introduces a support/url package and a URL struct for convenient url modifications.

### CODE REVIEW

File: support/url/main.go [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+	q := gu.Query()
+	q.Del(key)
+	q.Add(key, val)
+	gu.RawQuery = q.Encode()
+	return URL(gu)
+}
+
+// String encodes all URL segments to a fully qualified URL string
+func (u URL) String() string {
+	gu := gUrl.URL(u)
```
Comment (nikhilsaraf) [inline support/url/main.go]: can we not just call u.String()? -- i.e. maybe just leave off this method altogether?

if not -- `return gUrl.URL(u).String()`, doesn't need the passthrough var `gu`

File: support/url/main.go [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+// URL wraps around the native golang URL struct to allow for custom methods
+type URL gUrl.URL
+
+// SetParam returns a new URL with the given param created or modified if already exists
+func (u URL) SetParam(key string, val string) URL {
+	gu := gUrl.URL(u)
+	q := gu.Query()
+	q.Del(key)
+	q.Add(key, val)
+	gu.RawQuery = q.Encode()
```
Comment (nikhilsaraf) [inline support/url/main.go]: why do we need to call q.Encode() here, will it still work if we just delete this line?
it seems hacky to override `gu.RawQuery`, almost like we're setting values on `gu` twice.

File: services/horizon/internal/actions_trade.go [hunk 3]
```diff
@@ -172,9 +171,7 @@ func (action *TradeAggregateIndexAction) loadPage() {
 	action.Page.Limit = action.PagingParams.Limit
 	action.Page.Order = action.PagingParams.Order
 
-	newUrl := action.BaseURL()              // preserve scheme and host for the new url links
-	newUrl.RawQuery = action.R.URL.RawQuery //preserve query parameters
-	newUrl.Path = action.Path()             //preserve path
+	newUrl := action.FullURL()              // preserve scheme and host for the new url links
```
Comment (nikhilsaraf) [inline services/horizon/internal/actions_trade.go]: 👍  for a cleaner code pattern

File: services/horizon/internal/actions_assets_test.go [hunk 4]
```diff
@@ -243,9 +243,9 @@ func TestAssetsActions(t *testing.T) {
 				}
 			}
 
-			ht.Assert.Equal(("http://localhost" + kase.wantSelf), links.Self.Href)
-			ht.Assert.Equal(("http://localhost" + kase.wantPrevious), links.Prev.Href)
-			ht.Assert.Equal(("http://localhost" + kase.wantNext), links.Next.Href)
+			ht.Assert.EqualUrlStrings("http://localhost" + kase.wantSelf, links.Self.Href)
```
Comment (nikhilsaraf) [inline services/horizon/internal/actions_assets_test.go]: I don't think you have `gofmt` enabled on save? --that would have removed the `" "` around the `+` here, which is why I had the `()`

File: services/horizon/internal/actions_assets.go [hunk 5]
```diff
@@ -88,5 +87,5 @@ func (action *AssetsAction) loadPage() {
 	if action.AssetIssuer != "" {
 		linkParams.Set("asset_issuer", action.AssetIssuer)
 	}
-	action.Page.PopulateLinksWithParams(linkParams)
```
Comment (nikhilsaraf) [inline services/horizon/internal/actions_assets.go]: you should also remove the `linkParams` var here since it's no longer used --your compiler should have issued warning about this?

File: services/horizon/internal/action.go [hunk 6]
```diff
@@ -140,7 +140,15 @@ func (action *Action) EnsureHistoryFreshness() {
...
+func (action *Action) FullURL() *url.URL {
+	result := action.BaseURL()
+	result.Path = action.R.URL.Path
+	result.RawQuery = action.R.URL.RawQuery
+	return result
+}
+
+// BaseURL returns the base url for this request, defined as a url containing
 // the Host and Scheme portions of the request uri.
 func (action *Action) BaseURL() *url.URL {
```
Comment (nikhilsaraf) [inline services/horizon/internal/action.go]: if `FullURL` is the only consumer of `BaseURL` now then we should lowercase this method name.

File: services/horizon/internal/render/hal/page.go [hunk 7]
```diff
@@ -39,37 +41,40 @@ type Links struct {
 type Page struct {
 	Links Links `json:"_links"`
 	BasePage
-	BasePath string `json:"-"`
+	//BasePath string `json:"-"`
```
Comment (nikhilsaraf) [inline services/horizon/internal/render/hal/page.go]: delete instead of commenting out

File: services/horizon/internal/render/hal/page.go [hunk 8]
```diff
@@ -39,37 +41,40 @@ type Links struct {
...
-	if len(encodedParams) > 0 {
-		fmts = fmts + "&" + encodedParams
-	}
-	lb := LinkBuilder{p.BaseURL}
 
-	p.Links.Self = lb.Linkf(fmts, p.Order, p.Limit, p.Cursor)
 	rec := p.Embedded.Records
 
+	//verify paging params
+	selfUrl := sUrl.URL(*p.FullURL).
```
Comment (nikhilsaraf) [inline services/horizon/internal/render/hal/page.go]: don't think you need the `*` here.

File: support/url/main.go (hunk 2 above)
Comment (tomerweller) [reply support/url/main.go]: `RawQuery` is a string. The `Query()` function decodes current `RawQuery` string and returns a `Values` struct. I don't see another way to do this.

File: support/url/main.go (hunk 1 above)
Comment (tomerweller) [reply support/url/main.go]: In order to do that, you'd need to convert the sURL into a gURL every-time you want to call it...
Removing the passthrough var.

Comment (tomerweller) [reply support/url/main.go]: Maybe @nullstyle or one of the golang experts can weigh in on this.

File: support/url/main.go (hunk 2 above)
Comment (nikhilsaraf) [reply support/url/main.go]: what I'm suggesting is -- is `gu.RawQuery = q.Encode()` a nop here?

Comment (tomerweller) [reply support/url/main.go]: No, unfortunately this is how the `URL` struct is built

**Comment by nikhilsaraf** [comment]
See the one travis failure before merging.

**Comment by tomerweller** [comment]
@nullstyle I went ahead and merged this. When your table clears you can take a look to see if you have some feedback from an idiomatic perspective. not urgent at all.

File: services/horizon/internal/render/hal/page.go [hunk 9]
```diff
@@ -1,13 +1,15 @@
 package hal
 
 import (
+	sUrl "github.com/stellar/go/support/url"
```
Comment (nullstyle) [inline services/horizon/internal/render/hal/page.go]: package names should always be lower cased:  https://blog.golang.org/package-names

We should do the same with our aliases, IMO

File: support/url/main.go [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+
+// URL wraps around the native golang URL struct to allow for custom methods
+type URL gUrl.URL
+
+// SetParam returns a new URL with the given param created or modified if already exists
+func (u URL) SetParam(key string, val string) URL {
+	gu := gUrl.URL(u)
+	q := gu.Query()
+	q.Del(key)
+	q.Add(key, val)
```
Comment (nullstyle) [inline support/url/main.go]: instead of using `Del` then `Add`, just use `Set`.

Comment (nullstyle) [reply support/url/main.go]: https://golang.org/src/net/url/url.go?s=22624:22662#L779

File: support/url/main.go [hunk 11]
```diff
@@ -0,0 +1,34 @@
+package url
+
+import (
+	gUrl "net/url"
+)
+
+// URL wraps around the native golang URL struct to allow for custom methods
+type URL gUrl.URL
```
Comment (nullstyle) [inline support/url/main.go]: I'm not really happy with this whole type.   Go isn't an object-oriented language and this smells too much like you're trying to derive a subtype of URL so you can override some methods.  Instead of pretending this type is a `URL` lets call this type a `URLBuilder` and lets have it wrap a `url.URL`, not alias it.

See https://github.com/lann/builder for a pretty well worn implementation of the fluent builder pattern you are proposing here.
