### PR TITLE
Fix deadlock in `txsub.System.Tick()` and `tx_bad_seq` errors

### LINKED ISSUE #305: Horizon timeout after transaction is added to ledger
- See the following transaction: 
 https://horizon.stellar.org/transactions/335b869b7c9eb491291869b8b06b32582190395945cccb91457ba04774f3ace0
- This transaction was submitted to Horizon on `2018-02-12T15:12:19.31094599Z`. Looking at the transaction information, it was created on `2018-02-12T15:12:19Z`.
- Transaction added to ledger on: `2018-02-12T15:12:19Z` (~5 seconds after submission): https://horizon.stellar.org/ledgers/16230126
- Horizon replied with an HTTP 504 (Gateway Timeout) on `2018-02-12T15:13:19.434419221Z` (~1 minute after submission).
- I've used the golang SDK, and my `horizon.Client.HTTP.Timeout` is set to 2 minutes.

This is reproducible on 4 identical machines on DigitalOcean. The instances are on DO's zones FRA1, SFO1, SGP1, NYC1

Each node is running Horizon + Core (watcher, non-validating) using [stellar/quickstart docker image](https://hub.docker.com/r/stellar/quickstart/) with this commit: https://github.com/stellar/docker-stellar-core-horizon/commit/aad080792989a8082cbffc0f58bd8e481957af86

A local application submits transactions to the local Horizon on each node.

Here is the following Core and Horizon configuration in use:

```toml
# stellar/quickstart specific
HTTP_PORT=11626
PUBLIC_HTTP_PORT=true
LOG_FILE_PATH=""
DATABASE="postgresql://dbname=core host=localhost user=stellar password=1"
CATCHUP_RECENT=1024

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

NODE_NAMES=[
"GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE  satoshipay1",
"GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT  satoshipay2",
"GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY  satoshipay3",
"GCGWABAQ6OUOVUGWJVPRJ5LWBIWYN3CVOVOZYBNQQGIBRULQHYNGQ7GH  cryptomover1",
"GC7MH45NSXXPBLQJRSEVF2DFUVLGGYOJER5FRUNVCYVMXJYJT5LLQJW5  cryptomover2",
"GAENPO2XRTTMAJXDWM3E3GAALNLG4HVMKJ4QF525TR25RI42YPEDULOW  ibm_uk",
"GBJ7T3BTLX2BP3T5Q4256PUF7JMDAB35LLO32QRDYE67TDDMN7H33GGE  ibm_hong_kong",
"GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH  sdf1",
"GCM6QMP3DLRPTAZW2UZPCPX2LF3SXWXKPMP3GKFZBDSF3QZGV2G5QSTK  sdf2",
"GABMKJM6I25XI4K7U6XWMULOUQIQ27BCTMLS6BYYSOWKTBUXVRJSXHYQ  sdf3",
]

KNOWN_PEERS=[
"core-live-a.stellar.org:11625",
"core-live-b.stellar.org:11625",
"core-live-c.stellar.org:11625",
"confucius.strllar.org",
#"stellar1.bitventure.co",
"stellar.256kw.com"
]

[QUORUM_SET]
#VALIDATORS=[
#"$eno", "$tempo.eu.com", "$satoshipay", "$cryptomover", "$umbrel", "$exodo", "$ibm", "$sdf_watcher1", "$sdf_watcher2", "$sdf_watcher3"
#]
VALIDATORS=[
"$sdf1", "$sdf2", "$sdf3", "$satoshipay1", "$satoshipay2", "$satoshipay3", "$cryptomover1", "$cryptomover2", "$ibm_uk", "$ibm_hong_kong"
]


[HISTORY.cache]
get="cp /opt/stellar/history-cache/{0} {1}"

[HISTORY.sdf1]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"

[HISTORY.sdf2]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"

[HISTORY.sdf3]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"
```
```bash
#!/bin/bash

export DATABASE_URL="postgres://stellar:1@localhost/horizon"
export STELLAR_CORE_DATABASE_URL="postgres://stellar:1@localhost/core"
export STELLAR_CORE_URL="http://localhost:11626"
export LOG_LEVEL="info"
export INGEST="true"
export PER_HOUR_RATE_LIMIT="72000"
export NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
```
It looks like the configuration is OK, no idea why I'm getting the timeouts.

### PR DESCRIPTION
**Pull request by bartekn**
This commit fixes two issues in `txsub` package. First, issue was a
deadlock in `Tick()` function:

```go
sys.tickMutex.Lock()
if sys.tickInProgress {
  logger.Debug("ticking in progress")
  return
}
sys.tickInProgress = true
sys.tickMutex.Unlock()
```

When two `Tick()` methods were called simultanously one of them could
`Lock()` the mutex without calling `Unlock()` properly. This could
basically break the `txsub` system as sequence number could not be
updated.

The second issue was a problem with `App` initialization.
`App.networkPassphrase` was set to test network passphrase by default.
If `txsub` system was initialized before updating the network passphrase
using connected `stellar-core`, the system would not be able to
correctly find the transaction result in a database as calculated hash
was different than the actual hash of the transaction.

Close #305.

### CODE REVIEW

File: services/horizon/internal/app.go [hunk 1]
```diff
@@ -270,6 +270,13 @@ func (a *App) UpdateStellarCoreInfo() {
...
 
+	// Check if NetworkPassphrase is different, if so exit Horizon as it can break the
+	// state of the application.
+	if resp.Info.Network != a.networkPassphrase {
+		log.Error("Network passhprase of stellar-core does not match Horizon configuration. Exiting...")
+		os.Exit(1)
+	}
+
 	a.coreVersion = resp.Info.Build
 	a.networkPassphrase = resp.Info.Network
```
Comment (tomquisel) [inline services/horizon/internal/app.go]: This line can be removed now, right?

File: services/horizon/internal/app.go [hunk 2]
```diff
@@ -270,6 +270,13 @@ func (a *App) UpdateStellarCoreInfo() {
 		return
 	}
 
+	// Check if NetworkPassphrase is different, if so exit Horizon as it can break the
+	// state of the application.
+	if resp.Info.Network != a.networkPassphrase {
+		log.Error("Network passhprase of stellar-core does not match Horizon configuration. Exiting...")
```
Comment (tomquisel) [inline services/horizon/internal/app.go]: change `passhprase` to `passphrase`, and maybe improve error message to print the two passphrase values.

File: services/horizon/internal/app.go [hunk 3]
```diff
@@ -64,7 +64,7 @@ func NewApp(config Config) (*App, error) {
 
 	result := &App{config: config}
 	result.horizonVersion = app.Version()
-	result.networkPassphrase = build.TestNetwork.Passphrase
+	result.networkPassphrase = config.NetworkPassphrase
```
Comment (tomquisel) [inline services/horizon/internal/app.go]: Could we remove `App.networkPassphrase` and just use `App.Config.NetworkPassphrase` as the single source of truth?

File: services/horizon/internal/txsub/system.go [hunk 4]
```diff
@@ -178,7 +187,8 @@ func (sys *System) Tick(ctx context.Context) {
 	// Make sure Tick is not run concurrently
 	sys.tickMutex.Lock()
```
Comment (tomquisel) [inline services/horizon/internal/txsub/system.go]: I might accomplish this locking with two functions:

`SetTickInProgress`:
```
        sys.tickMutex.Lock()
        defer sys.tickMutex.Unlock()
	if sys.tickInProgress {
		logger.Debug("ticking in progress")
		return false
	}
	sys.tickInProgress = true
        return true
```

`UnsetTickInProgress`:
```
        sys.tickMutex.Lock()
        defer sys.tickMutex.Unlock()
        sys.tickInProgress = false 
```

and then call those from `Tick` (which checks the results of `SetTickInProgress` and exits if `false`, and calls `UnsetTickInProgress()` in `defer`.

I think that'd make this a little safer from this kind of bug in the future.

File: services/horizon/main.go [hunk 5]
```diff
@@ -239,6 +239,10 @@ func initConfig() {
 		stdLog.Fatal("Invalid config: stellar-core-url is blank.  Please specify --stellar-core-url on the command line or set the STELLAR_CORE_URL environment variable.")
 	}
 
+	if viper.GetString("network-passphrase") == "" {
+		stdLog.Fatal("Invalid config: network-passphrase is blank.  Please specify --network-passphrase on the command line or set the NETWORK_PASSPHRASE environment variable.")
+	}
+
```
Comment (tomquisel) [inline services/horizon/main.go]: Hrm, is it a breaking change to make this required? It seems like it might be, and it'd be better to leave `network-passphrase` optional + default to testnet as we do currently.

**Comment by oryband** [comment]
I've tested this branch in an environment where I can reproduce the issue and the problem is solved.

File: services/horizon/internal/txsub/system.go (hunk 4 above)
Comment (bartekn) [reply services/horizon/internal/txsub/system.go]: Good point. The ultimate solution is to remove global ticking service completely (#613). It caused a lot of concurrency problems in the past (including this one) and can be implemented much easier using infinite loop.

File: services/horizon/main.go (hunk 5 above)
Comment (bartekn) [reply services/horizon/main.go]: Good point, set default value to testnet passphrase but in the next minor we need to make this empty by default. Ex. if you run ingestion node without web server and when stellar-core is not running it should be explicitly set by Horizon admin (#817).

**Comment by bartekn** [comment]
@oryband thanks for checking this. Would you mind checking this again in your environment (I pushed one last commit with updates).
@tomquisel all good points, fixed and added 2 comments.

**Comment by oryband** [comment]
@bartekn I tested this again. It works. Thanks for sorting this issue out! :trophy:

**Comment by oryband** [comment]
@bartekn do you know when you'll release a new stable version that includes this branch?

**Comment by bartekn** [comment]
@oryband today.

**Comment by oryband** [comment]
WHOOHOO.

File: services/horizon/internal/txsub/system.go [hunk 6]
```diff
@@ -170,25 +179,40 @@ func (sys *System) submitOnce(ctx context.Context, env string) SubmissionResult
 	return sr
 }
 
+// setTickInProgress sets `tickInProgress` to `true` if it's not
```
Comment (howardtw) [inline services/horizon/internal/txsub/system.go]: Looks like we set `tickInProgress` to `true` only if it is `false`?

File: services/horizon/internal/txsub/system.go [hunk 7]
```diff
@@ -73,12 +74,20 @@ func (sys *System) Submit(ctx context.Context, env string) (result <-chan Result
 	// check the configured result provider for an existing result
 	r := sys.Results.ResultByHash(ctx, info.Hash)
 
-	if r.Err != ErrNoResults {
+	if r.Err == nil {
```
Comment (howardtw) [inline services/horizon/internal/txsub/system.go]: Nothing wrong with the logic here but what is the reason that we have an Err field in r as oppose to have ResultByHash return r and err directly?

Comment (bartekn) [reply services/horizon/internal/txsub/system.go]: It's also used as an object returned by channel.

File: services/horizon/internal/txsub/system.go (hunk 6 above)
Comment (bartekn) [reply services/horizon/internal/txsub/system.go]: Good catch! https://github.com/stellar/go/pull/824
