### PR TITLE
[services/friendbot] Return HTTP 400 when the account submitted to friendbot already exists

### LINKED ISSUE #1511: Friendbot responds with 500 error if you double-fund an account
It may actually be crashing the server, since the response is slow. So we have two goals:

- make sure the crash is fixed (if there is one)
- respond with a 400 rather than a 500 error if the account cannot be created for any reason including double-funding

### PR DESCRIPTION
**Pull request by nikhilsaraf**
fixes #1511 

<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [x] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### Summary

Funding an account with friendbot used to return an HTTP 500. This PR addresses that and returns a HTTP 400

### Goal and scope

Fix error code returned with an informative error message

### Summary of changes

Register the friendbot account exists error so we treat it as a bad request HTTP 400 

### Known limitations & issues

None that i can think of

### What shouldn't be reviewed

N/A

### CODE REVIEW

File: services/friendbot/init_friendbot.go [hunk 1]
```diff
@@ -109,7 +110,12 @@ func createMinionAccounts(botAccount internal.Account, botKeypair *keypair.Full,
 		}
 		resp, err := hclient.SubmitTransactionXDR(txe)
 		if err != nil {
-			log.Print(resp)
+			log.Println(resp)
+			switch e := err.(type) {
+			case *horizonclient.Error:
```
Comment (nikhilsaraf) [inline services/friendbot/init_friendbot.go]: when there's any issue with creating minions, this will give us a more informed error message

File: services/friendbot/internal/friendbot_handler.go [hunk 2]
```diff
@@ -17,6 +17,10 @@ type FriendbotHandler struct {
 
 // Handle is a method that implements http.HandlerFunc
 func (handler *FriendbotHandler) Handle(w http.ResponseWriter, r *http.Request) {
+	accountExistsProblem := problem.BadRequest
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot_handler.go]: register problem so it can be returned as an HTTP 400 bad request message

File: services/friendbot/internal/minion.go [hunk 3]
```diff
@@ -58,6 +60,9 @@ func SubmitTransaction(minion *Minion, hclient *horizonclient.Client, tx string)
 			resStr, resErr := e.ResultString()
 			if resErr != nil {
 				errStr += ": error getting horizon error code: " + resErr.Error()
+			} else if resStr == "AAAAAAAAAGT/////AAAAAQAAAAAAAAAA/////AAAAAA=" {
```
Comment (nikhilsaraf) [inline services/friendbot/internal/minion.go]: return a fixed error if the account doesn't exist and map this error to Bad Request in the caller

File: services/friendbot/init_friendbot.go [hunk 4]
```diff
@@ -109,7 +110,12 @@ func createMinionAccounts(botAccount internal.Account, botKeypair *keypair.Full,
 		}
 		resp, err := hclient.SubmitTransactionXDR(txe)
 		if err != nil {
-			log.Print(resp)
+			log.Println(resp)
```
Comment (debnil) [inline services/friendbot/init_friendbot.go]: Do we want to always log the response in case of an error, given that we have the more fine-grained case of a Horizon client error now?

File: services/friendbot/internal/minion.go [hunk 5]
```diff
@@ -8,6 +8,8 @@ import (
 	"github.com/stellar/go/txnbuild"
 )
 
+var ErrAccountExists error = errors.New("createAccountAlreadyExist (AAAAAAAAAGT/////AAAAAQAAAAAAAAAA/////AAAAAA=)")
```
Comment (debnil) [inline services/friendbot/internal/minion.go]: Given that you use the XDR for bad result in multiple places, does it make sense to have this as a constant?

File: services/friendbot/init_friendbot.go (hunk 4 above)
Comment (nikhilsaraf) [reply services/friendbot/init_friendbot.go]: yeah, I think it's ok to log, with friendbot being very moody in the past I'd rather have the extra log lines.

**Comment by nikhilsaraf** [comment]
@debnil updated, if still good then i'll merge it in
