### PR TITLE
Fix invalid account params message.

### LINKED ISSUE #1926: Error message in /accounts invalid when no params
```
{
  "type": "https://stellar.org/horizon-errors/invalid_accounts_params",
  "title": "Invalid Accounts Parameters",
  "status": 400,
  "detail": "A filter is required. Please ensure that you are including a signer or an asset (asset_type, asset_issuer and asset_code)."
}
```
After #1835 asset is passed using `asset` param instead of `asset_type`, `asset_issuer` and `asset_code`.

### PR DESCRIPTION
**Pull request by abuiles**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Fix the message to include the right format for asset.  Fixes #1926 1926

### Why

After #1835, asset is passed using asset param instead of asset_type, asset_issuer and asset_code.

### Known limitations

N/A

### CODE REVIEW

File: services/horizon/internal/actions/account.go [hunk 1]
```diff
@@ -267,7 +267,7 @@ var invalidAccountsParams = problem.P{
 	Type:   "invalid_accounts_params",
 	Title:  "Invalid Accounts Parameters",
 	Status: http.StatusBadRequest,
-	Detail: "A filter is required. Please ensure that you are including a signer or an asset (asset_type, asset_issuer and asset_code).",
+	Detail: "A filter is required. Please ensure that you are including a signer or an asset.",
```
Comment (bartekn) [inline services/horizon/internal/actions/account.go]: Do you think it's worth including a format (`code:issuer`) here? Either way: 👍

Comment (abuiles) [reply services/horizon/internal/actions/account.go]: I'll say let's keep it like this, however that makes me wonder how can we improve API params documentation.
