### PR TITLE
services/ticker: handle invalid TOML urls gracefully

### LINKED ISSUE #2326: services/ticker crash on "ingest assets"
### What did you do?

I was trying to ingest asset data into fresh DB like this:
```
ticker ingest assets --db-url=XXX
```

### What did you expect to see?

Successful run

### What did you see instead?

It run for around 10s and then failed:
```
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9048" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9049" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9050" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9051" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9052" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9053" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9054" pid=1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8b8c22]

goroutine 401 [running]:
github.com/stellar/go/services/ticker/internal/scraper.fetchTOMLData(0xc000650140, 0x35, 0x0, 0xc00056b530, 0x10, 0xc00056b529, 0x3, 0xc000650180, 0x38, 0xc000578ff0, ...)
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:78 +0x122
github.com/stellar/go/services/ticker/internal/scraper.processAsset(0xc000650140, 0x35, 0x0, 0xc00056b530, 0x10, 0xc00056b529, 0x3, 0xc000650180, 0x38, 0xc000578ff0, ...)
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:218 +0x1c2
github.com/stellar/go/services/ticker/internal/scraper.(*ScraperConfig).parallelProcessAssets.func1(0x13, 0x2450, 0xc00092c000, 0x2450, 0x2a49, 0xf02a01, 0xc00050e0c0, 0xc00050e0b8, 0xc0001be6c0, 0x153a)
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:256 +0x264
created by github.com/stellar/go/services/ticker/internal/scraper.(*ScraperConfig).parallelProcessAssets
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:247 +0x1e4
```

Extra info:
If I add "--testnet" flag it works fine

### PR DESCRIPTION
**Pull request by accordeiro**
### What

Ensure the Ticker can gracefully handle invalid TOML urls.

### Why

This PR fixes #2326. We were missing an error check after creating an HTTP request to catch invalid URLs / requests.

### CODE REVIEW

File: services/ticker/internal/scraper/asset_scraper.go [hunk 1]
```diff
@@ -69,6 +69,12 @@ func fetchTOMLData(asset hProtocol.AssetStat) (data string, err error) {
...
 
+	_, err = url.ParseRequestURI(tomlURL)
+	if err != nil {
+		err = errors.New("Asset has an invalid TOML URL")
+		return
+	}
+
 	timeout := time.Duration(10 * time.Second)
 	client := http.Client{
 		Timeout: timeout,
```
Comment (leighmcculloch) [inline services/ticker/internal/scraper/asset_scraper.go]: The issue is actually a few lines down. You need to check that the err returned from NewRequest is nil. It isn't nil and the req is nil which is what is causing the error.

Comment (leighmcculloch) [reply services/ticker/internal/scraper/asset_scraper.go]: The NewRequest call already validates the URL so you don't need to do it above.

Comment (accordeiro) [reply services/ticker/internal/scraper/asset_scraper.go]: You're right, my bad. Pushing a fix now :)

**Comment by accordeiro** [comment]
Done! @leighmcculloch should be good for another look :)

File: services/ticker/internal/scraper/asset_scraper.go [hunk 2]
```diff
@@ -75,8 +75,12 @@ func fetchTOMLData(asset hProtocol.AssetStat) (data string, err error) {
 	}
 
 	req, err := http.NewRequest("GET", tomlURL, nil)
-	req.Header.Set("User-Agent", "Stellar Ticker v1.0")
+	if err != nil {
+		err = errors.New("Invalid URL or request")
```
Comment (leighmcculloch) [inline services/ticker/internal/scraper/asset_scraper.go]: Use a lower case first character because nested errors get concatenated, the Go linter will pickup on this but we don't seem to run it on CI. Also wrap the error so we can see exactly what's wrong with the URL in the caller or wherever this might be outputted if it is today or ever gets outputted in the future. You'll need to import `github.com/stellar/go/support/errors` to get the Wrap call.
```suggestion
		err = errors.Wrap(err, "invalid URL or request")
```

File: services/ticker/internal/scraper/asset_scraper_test.go [hunk 3]
```diff
@@ -129,3 +130,12 @@ func TestIsDomainVerified(t *testing.T) {
...
 	assert.False(t, isDomainVerified(orgURL, tomlURL, hasCurrency))
 }
+
+func TestIgnoreInvalidTOMLUrls(t *testing.T) {
+	invalidURL := "https:// there is something wrong here.com/stellar.toml"
+	assetStat := hProtocol.AssetStat{}
+	assetStat.Links.Toml = hal.Link{Href: invalidURL}
+
+	_, err := fetchTOMLData(assetStat)
+	assert.Error(t, err)
```
Comment (leighmcculloch) [inline services/ticker/internal/scraper/asset_scraper_test.go]: You can use the `EqualError` function to provide a string that the error should match and it'd make this test clearer I think.

File: services/ticker/internal/scraper/asset_scraper.go (hunk 2 above)
Comment (accordeiro) [reply services/ticker/internal/scraper/asset_scraper.go]: Done, thanks for the suggestions! :)

File: services/ticker/internal/scraper/asset_scraper_test.go (hunk 3 above)
Comment (accordeiro) [reply services/ticker/internal/scraper/asset_scraper_test.go]: Done!
