### PR TITLE
Friendbot as a Microservice

### LINKED ISSUE #134: Friendbot non-deterministically fails "400: tx_bad_seq"
The following requests fails the first time, but succeeded on a subsequent attempt. This has happened several times for me and I was able to repro it:

request: `GET https://horizon-testnet.stellar.org/friendbot?addr=GDE626U3V4XGLBXOIYAWYWTJCDCB2KI2WG36JX6NPOO4UUC7PK2I7S6E`

account_address: `GDE626U3V4XGLBXOIYAWYWTJCDCB2KI2WG36JX6NPOO4UUC7PK2I7S6E`
status_code_number: `400`
timestamp: `2017-10-27T15:46:06.091371`
response:
```
"{\n  \"type\": \"https://stellar.org/horizon-errors/transaction_failed\",\n  \"title\": \"Transaction Failed\",\n  \"status
\": 400,\n  \"detail\": \"The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html\",\n 
 \"instance\": \"horizon-testnet-001/oC37glgPdv-3417608\",\n  \"extras\": {\n    \"envelope_xdr\": \"AAAAAGXNhLrhGtltTwCpmqlarh7s1DB2hIkbP//jgzn4Fos/AAAAZAAACT0AAJTsAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAye16m68uZYbuRg
FsWmkQxB0pGrG35N/Ne53KUF96tI8AAAAXSHboAAAAAAAAAAAB+BaLPwAAAECExNaEr8h1Blx+WrvweQjz9wERIc/jLFm+lrzPMnIuRIL8zrv4y6SMzGa3+yFJMt6GzBnSXkibWfahyKT1YDgP\",\n    \"result_codes\": {\n      \"transaction\": \"tx_bad_seq\"\n    },\n    \"result_xdr\": \"AAAAAAAAAAD////7AAAAAA==\"\n  }\n}"
```

### PR DESCRIPTION
**Pull request by nikhilsaraf**
Extracted out Friendbot into it's own microservice so we can run it independently.

The friendbot microservice will call out to Horizon over HTTP/S, taking the horizon url from a new config file. Horizon will temporarily redirect all incoming requests (`/friendbot`) to the passed in friendbot_url at `/` along with the request query params.

This PR is a working separation of friendbot and is ready to merge from a functional perspective. It may be easier to review the code in the following logical order of the 3 commits.
- [x] Commit 1: Extract out common packages used by both Friendbot and Horizon out of `horizon/internal` (many changed files)
- [x] Commit 2: Extract Friendbot out of Horizon into it's own microservice
- [x] Commit 3: Redirect `/friendbot` on horizon to `/` on friendbot

------

In order to prevent merge conflicts from code drift and to keep the code more easily reviewable, I plan to have a second PR with additional improvements. This PR closes #134 and I will open a new issue for the leftover work outlined below.
- clean up middleware (logging, rate limiting, metrics)
- doc updates (horizon and friendbot)
- use [go-chi/chi](https://github.com/go-chi/chi) as mux

### CODE REVIEW

File: services/friendbot/internal/friendbot.go [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+	Secret          string
+	Network         string
+	StartingBalance string
+
+	sequence uint64
+	lock     sync.Mutex
+}
+
+// Pay funds the account at `destAddress`
+func (bot *Bot) Pay(destAddress string) (client.TransactionSuccess, error) {
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot.go]: reworked this file to use the client/horizon library to build a CreateAccount operation instead of using the txsub.

File: services/friendbot/internal/friendbot_test.go [hunk 2]
```diff
@@ -1,27 +1,24 @@
-package friendbot
+package internal
 
 import (
 	"testing"
 
-	"sync"
+	"github.com/stretchr/testify/assert"
 
-	"github.com/stellar/go/services/horizon/internal/test"
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot_test.go]: removed the horizon/internal/test dependency since we don't need it here

File: services/friendbot/main.go [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+	"golang.org/x/net/http2"
+)
+
+// TLSConfig specifies the TLS portion of the config
+type TLSConfig struct {
+	CertificateFile string `toml:"certificate-file" valid:"required"`
+	PrivateKeyFile  string `toml:"private-key-file" valid:"required"`
+}
+
+// Config represents the configuration of a friendbot server
```
Comment (nikhilsaraf) [inline services/friendbot/main.go]: follows the command pattern in federation as opposed to what we do in horizon

File: services/friendbot/main.go [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+	appWeb := initWeb()
+	fb := initFriendbot(cfg.FriendbotSecret, cfg.NetworkPassphrase, cfg.HorizonURL, cfg.StartingBalance)
+	initRouter(appWeb.router, fb)
+
+	Serve(appWeb.router, cfg.Port, cfg.TLS)
+}
+
+// Web contains the http server related fields for horizon: the router,
+// rate limiter, etc.
+type Web struct {
```
Comment (nikhilsaraf) [inline services/friendbot/main.go]: this Web and initWeb will go away once we move to using the `go-chi/chi` mux. Used this for now since it was closely tied to our Action pattern and I wanted to keep that as a smooth extraction/refactor.

File: services/friendbot/internal/actions_friendbot.go [hunk 5]
```diff
@@ -1,35 +1,36 @@
...
 func (action *FriendbotAction) JSON() {
-
 	action.Do(
 		action.checkEnabled,
 		action.loadAddress,
 		action.loadResult,
-		action.loadResource,
-
 		func() {
-			hal.Render(action.W, action.Resource)
```
Comment (nikhilsaraf) [inline services/friendbot/internal/actions_friendbot.go]: since we use `hal`, I needed to move `horizon/internal/render` to `horizon/render`

File: services/friendbot/internal/friendbot.go [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+
+	if txn.Err != nil {
+		return "", txn.Err
+	}
+
+	txs := txn.Sign(bot.Secret)
+	base64, err := txs.Base64()
+
+	// only increment the in-memory sequence number if we are going to submit the transaction, while we hold the lock
+	if err == nil {
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot.go]: small functional change here: I moved the bot sequence increment to be after we sign the txn as opposed to before we sign. this way we only increment if we will be sending to the network.

File: services/horizon/internal/init_web.go [hunk 7]
```diff
@@ -50,15 +51,15 @@ func initWeb(app *App) {
 func initWebMiddleware(app *App) {
 
 	r := app.web.router
-	r.Use(stripTrailingSlashMiddleware())
+	r.Use(hm.StripTrailingSlashMiddleware())
 	r.Use(middleware.EnvInit)
 	r.Use(app.Middleware)
 	r.Use(middleware.RequestID)
-	r.Use(contextMiddleware(app.ctx))
```
Comment (nikhilsaraf) [inline services/horizon/internal/init_web.go]: extracted some middleware that is shared between horizon and friendbot. Happy to move this elsewhere if you want but we needed it for now so I moved it out of `horizon/internal`

File: services/horizon/internal/init_web.go [hunk 8]
```diff
@@ -125,8 +126,12 @@ func initWebActions(app *App) {
 	r.Get("/assets", &AssetsAction{})
 
 	// friendbot
-	r.Post("/friendbot", &FriendbotAction{})
-	r.Get("/friendbot", &FriendbotAction{})
+	redirectFriendbot := func(w http.ResponseWriter, r *http.Request) {
```
Comment (nikhilsaraf) [inline services/horizon/internal/init_web.go]: redirect operation from horizon

File: services/friendbot/internal/actions_friendbot.go (hunk 5 above)
Comment (nullstyle) [reply services/friendbot/internal/actions_friendbot.go]: It's not acceptable for us to introduce cross-service dependencies in this way.  It's too easy IMO for service-specific decisions to become implicit dependencies between the two services to arise and for us to get painted into a corner or a painful refactoring.

Instead, if you'd like to leverage the hal library in friendbot, extract the non-horizon-specific parts to`support/render/hal`.  `PagingToken`,`Page`, `StandardPagingOptions`, and `PagedLink` shouldn't be extracted owing to the fact that they are too horizon-specific.  Also, it'd be great if you can update the tests to reflect our latest best practices.

File: services/friendbot/main.go [hunk 9]
```diff
@@ -0,0 +1,159 @@
...
+	r.Use(middleware.AutomaticOptions)
+
+	c := cors.New(cors.Options{
+		AllowedOrigins: []string{"*"},
+		AllowedHeaders: []string{"*"},
+	})
+	r.Use(c.Handler)
+
+	// friendbot
+	r.Post("/", &internal.FriendbotAction{Friendbot: fb})
```
[the remark this answers is not in the document]
Comment (nikhilsaraf) [reply services/friendbot/main.go]: it was enabled in horizon. Horizon requests will be forwarded here so we still need to support POST requests.

File: services/friendbot/main.go [hunk 10]
```diff
@@ -0,0 +1,159 @@
...
+	return &Web{
+		router:       web.New(),
+		requestTimer: metrics.NewTimer(),
+		failureMeter: metrics.NewMeter(),
+		successMeter: metrics.NewMeter(),
+	}
+}
+
+func initRouter(r *web.Mux, fb *internal.Bot) {
+	ctx, _ := context.WithCancel(context.Background())
```
[the remark this answers is not in the document]
Comment (nikhilsaraf) [reply services/friendbot/main.go]: there's no context anymore

File: services/friendbot/internal/friendbot_test.go [hunk 11]
```diff
@@ -1,27 +1,24 @@
...
+		Secret:          "SAQWC7EPIYF3XGILYVJM4LVAVSLZKT27CTEI3AFBHU2VRCMQ3P3INPG5",
+		Network:         "Test SDF Network ; September 2015",
+		StartingBalance: "100.00",
+		sequence:        2,
 	}
 
 	_, err := fb.makeTx("GDJIN6W6PLTPKLLM57UW65ZH4BITUXUMYQHIMAZFYXF45PZVAWDBI77Z")
-
-	tt.Require.NoError(err)
+	assert.NoError(t, err)
```
[the remark this answers is not in the document]
Comment (nikhilsaraf) [reply services/friendbot/internal/friendbot_test.go]: done

**Comment by nikhilsaraf** [comment]
addressed comments, there's only 1 item left in my books:
- [ ] friendbot error message should match current hal format to be consistent with existing API.

File: services/friendbot/internal/friendbot.go [hunk 12]
```diff
@@ -0,0 +1,111 @@
...
+	}
+
+	// var envelope string
+	signed, err := bot.makeTx(destAddress)
+	if err != nil {
+		return client.TransactionSuccess{}, err
+	}
+
+	result, err := bot.Client.SubmitTransaction(signed)
+	if err != nil && strings.Contains(err.Error(), "tx_bad_seq") {
```
Comment (bartekn) [inline services/friendbot/internal/friendbot.go]: I think that `Error()` return value [does not](https://github.com/stellar/go/blob/master/clients/horizon/error.go#L11) contain the code. You should check `ResultCodes` method.

File: services/friendbot/internal/friendbot.go [hunk 13]
```diff
@@ -0,0 +1,111 @@
...
+	base64, err := txs.Base64()
+
+	// only increment the in-memory sequence number if we are going to submit the transaction, while we hold the lock
+	if err == nil {
+		bot.sequence++
+	}
+	return base64, err
+}
+
+// refreshes the sequence from the bot account and increments by 1
```
Comment (bartekn) [inline services/friendbot/internal/friendbot.go]: Outdated part of comment: `and increments by 1`

File: services/friendbot/internal/friendbot.go [hunk 14]
```diff
@@ -0,0 +1,111 @@
...
+func (bot *Bot) refreshSequence() error {
+	botAccount, err := bot.Client.LoadAccount(bot.address())
+	if err != nil {
+		return err
+	}
+
+	seq, err := strconv.ParseInt(botAccount.Sequence, 10, 0)
+	if err != nil {
+		return err
+	}
```
Comment (bartekn) [inline services/friendbot/internal/friendbot.go]: In case of errors in this function, would it help to reset sequence number to `0`? Then in `checkRefreshSequence` it will attempt to load it again instead of submitting tx with invalid one.

Comment (nikhilsaraf) [reply services/friendbot/internal/friendbot.go]: done

File: services/friendbot/internal/friendbot.go (hunk 13 above)
Comment (nikhilsaraf) [reply services/friendbot/internal/friendbot.go]: removed

File: services/friendbot/internal/friendbot.go (hunk 12 above)
Comment (nikhilsaraf) [reply services/friendbot/internal/friendbot.go]: fixed

**Comment by nikhilsaraf** [comment]
Good to go on my end, @nullstyle @bartekn

File: services/friendbot/internal/friendbot.go [hunk 15]
```diff
@@ -0,0 +1,125 @@
...
+		return nil, err
+	}
+
+	result, err := bot.Client.SubmitTransaction(signed)
+	if err != nil {
+		switch e := err.(type) {
+		case client.Error:
+			bot.checkHandleBadSequence(&e)
+		case *client.Error:
+			bot.checkHandleBadSequence(e)
```
Comment (bartekn) [inline services/friendbot/internal/friendbot.go]: Why? Shouldn't we always return the same error type?

File: services/horizon/internal/init_web.go [hunk 16]
```diff
@@ -125,8 +126,12 @@ func initWebActions(app *App) {
...
+		redirectURL := app.config.FriendbotURL + "?" + r.URL.RawQuery
+		http.Redirect(w, r, redirectURL, http.StatusTemporaryRedirect)
+	}
```
Comment (bartekn) [inline services/horizon/internal/init_web.go]: IMHO, we should remove friendbot completely and add path-based routing at proxy level.

File: support/http/server/factory.go [hunk 17]
```diff
@@ -0,0 +1,27 @@
...
+
+	"github.com/go-chi/chi/middleware"
+)
+
+// EmptyConfig gives you a new empty Config
+func EmptyConfig() *Config {
+	router := make(map[string][]route)
+	for _, method := range supportedMethods {
+		router[method] = []route{}
+	}
```
Comment (bartekn) [inline support/http/server/factory.go]: We don't really need this. Maps hold default value (empty slice for slices) when there is no element yet. So `supportedMethods` is also unnecessary (we may want to add `DELETE` routes in a future).

File: services/friendbot/internal/friendbot.go (hunk 15 above)
Comment (nikhilsaraf) [reply services/friendbot/internal/friendbot.go]: the API returns type `error` although SubmitTransaction -> decodeResponse -> returns the pointer.
fixed.

File: services/horizon/internal/init_web.go (hunk 16 above)
Comment (nikhilsaraf) [reply services/horizon/internal/init_web.go]: yes, we should do that, was trying to reduce the ops overhead of making this dev change. This will still work and I can remove it once it's fully working via the proxy.

File: support/http/server/factory.go (hunk 17 above)
Comment (nikhilsaraf) [reply support/http/server/factory.go]: ok, updated.

**Comment by nikhilsaraf** [comment]
ping @nullstyle @bartekn

**Comment by nikhilsaraf** [comment]
made all the suggested changes, @nullstyle 

for `halRender`, we will need to include that separation since the `Render` method moved there. This just adds 1 import and 1 rename for these files. Since in a few cases there are more than 1 calls to the original `hal` package, renaming that would cause more diffs. I'm happy to go with whatever route is easier for you to review.

File: services/friendbot/internal/friendbot_handler.go [hunk 18]
```diff
@@ -20,15 +19,15 @@ type FriendbotHandler struct {
 func (handler *FriendbotHandler) Handle(w http.ResponseWriter, r *http.Request) {
 	result, err := handler.doHandle(r)
 	if err != nil {
-		problem.Render(log.DefaultLogger, w, err)
+		problem.Render(nil, w, err)
```
Comment (nullstyle) [inline services/friendbot/internal/friendbot_handler.go]: use `context.Background()` when no context is currently known.  However, you probably just want to use `r.Context()` in this situation.

**Comment by nikhilsaraf** [comment]
done, @nullstyle

File: support/http/server/chi-router.go [hunk 19]
```diff
@@ -0,0 +1,88 @@
...
+	// not found handler
+	if c.notFound != nil {
+		mux.NotFound(c.notFound)
+	}
+
+	return mux
+}
+
+// Serve starts a web server by binding it to a socket and setting up the shutdown signals
+func Serve(router *chi.Mux, port int, tls *TLSConfig) {
```
Comment (nullstyle) [inline support/http/server/chi-router.go]: I'm fine with us merging this code in the present state, but I think in general you should probably try to mirror the existing go http functions, keeping function signatures analogous when possible.  This method, for example, should probably be named `ListenAndServeTLS`, the router should be the last argument, and the port should probably just be a standard go listen string.

File: services/bifrost/server/server.go [hunk 20]
```diff
@@ -6,21 +6,20 @@ package server
 import (
```
Comment (nullstyle) [inline services/bifrost/server/server.go]: I just want to point out that we already have server helpers in our `support/http` package:  https://github.com/stellar/go/blob/master/support/http/main.go#L36

File: support/http/server/middleware_logger.go [hunk 21]
```diff
@@ -0,0 +1,46 @@
...
+
+	requestLog.WithFields(log.F{
+		"status":         ww.Status(),
+		"response_bytes": ww.BytesWritten(),
+		"duration":       duration.FloatString(8),
+	}).Info("HTTP response")
+}
+
+// BindLoggerMiddleware returns a LoggerMiddleware bound to the passed in requestIdKey, thereby decoupling it from middleware.RequestID
+func BindLoggerMiddleware(requestIDKey interface{}) func(http.Handler) http.Handler {
```
Comment (nullstyle) [inline support/http/server/middleware_logger.go]: Why do we need to bind the middleware to different request id keys?

File: support/http/server/middleware_logger.go [hunk 22]
```diff
@@ -0,0 +1,46 @@
...
+	})
+
+	requestLog.Info("HTTP request")
+
+	ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)
+	requestStartTime := time.Now()
+
+	next.ServeHTTP(ww, r)
+
+	duration := big.NewRat(
```
Comment (nullstyle) [inline support/http/server/middleware_logger.go]: Doing big math to calculate duraction is overkill IMO.  Accuracy is not paramount... lets just use floating point math.

File: support/log/entry.go [hunk 23]
```diff
@@ -37,8 +38,10 @@ func (e *Entry) WithFields(fields F) *Entry {
 func (e *Entry) WithStack(stackProvider interface{}) *Entry {
```
Comment (nullstyle) [inline support/log/entry.go]: I  We should probably expand this function to a type switch:

```go

func (e *Entry) WithStack(stackProvider interface{}) *Entry {
  var stack string
  switch sp := stackProvider.(type) {
    case errors.StackTracer:
      stack = fmt.Sprint(sp.StackTrace())
    case *gerr.Error:
      stack = fmt.Sprint(sp.ErrorStack())
    default:
      stack = "unknown"
  }

  return e.WithField("stack", stack)
}

```

File: support/log/main.go [hunk 24]
```diff
@@ -60,8 +56,11 @@ func Set(parent context.Context, logger *Entry) context.Context {
 // Ctx returns the logger bound to the provided context, otherwise
 // providing the default logger.
 func Ctx(ctx context.Context) *Entry {
-	found := ctx.Value(&contextKey)
+	if ctx == nil {
```
Comment (nullstyle) [inline support/log/main.go]: contexts should never be nil... that case represents a developer error, so IMO we should continue to panic if nil is provided.

File: support/http/server/middleware_logger.go (hunk 22 above)
Comment (nullstyle) [reply support/http/server/middleware_logger.go]: Scratch the recommendation of floating math.  Let's copy how horizon's logger middleware does it:

https://github.com/stellar/go/blob/master/services/horizon/internal/middleware_logger.go#L32-L34

File: support/http/server/middleware_logger.go [hunk 25]
```diff
@@ -0,0 +1,46 @@
...
+import (
+	"math/big"
+	"net/http"
+	"time"
+
+	"github.com/go-chi/chi/middleware"
+	"github.com/stellar/go/support/log"
+)
+
+func loggerMiddleware(requestIDKey interface{}, next http.Handler, w http.ResponseWriter, r *http.Request) {
```
Comment (nullstyle) [inline support/http/server/middleware_logger.go]: My primary concern about this logging package is that there is no way to support horizon from it at present.  We include additional fields in the request/response log lines in horizon:

https://github.com/stellar/go/blob/master/services/horizon/internal/middleware_logger.go#L63

I'd like to have a story about how we are going to support horizon before we commit to a common package.

**Comment by nullstyle** [comment]
I don't think any of the issues I've raised from this latest round are blockers, so I'm going to go ahead and approve a merge, but it'd be great if you could address the issues soon.
