### PR TITLE
Fix for transaction submission timeout

### LINKED ISSUE #5192: services/horizon/txsub: submitting transaction with future sequence may result in 60s timeout
### What version are you using?

2.28.0

### What did you do?

submit a tx with a sequence number that is gapped farther out than current source account seq+1.

```
curl --location 'https://<horizon_2.28.0_on_testnet>/transactions' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'tx=AAAAAgAAAACI3DQX1QWOxLRQPgwS6hoKib4gD+mJIkI9QzQBT6aw7gAAJxAAAYJ5AAABZAAAAAAAAAABAAAAHEJXUnhramQ5V3VkdXVrZXdrakN1dVVjQlk0YWgAAAABAAAAAQAAAACI3DQX1QWOxLRQPgwS6hoKib4gD+mJIkI9QzQBT6aw7gAAAAEAAAAAO5kROA7+mIugqJAOsc/kTzZvfb6Ua+0HckD39iTfFcUAAAAAAAAAAAAAA/IAAAAAAAAAAU+msO4AAABANwm//iyoc4FjpAp4awoQLQmakCKF4HNiNZp02fm+cHZtJ1QOKR6ZjZGPUipUj/AkyhYDtqOBMNfXvR49YExTCg=='

```

### What did you expect to see?
tx_bad_seq error returned

### What did you see instead?
60 second timeout from server

### PR DESCRIPTION
**Pull request by aditya1702**
<details>
  <summary>PR Checklist</summary>
  
### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `services/friendbot`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ ] I've updated any docs ([developer docs](https://developers.stellar.org/api/), `.md`
  files, etc... affected by this change). Take a look in the `docs` folder for a given service,
  like [this one](https://github.com/stellar/go/tree/master/services/horizon/internal/docs).

### Release planning

* [ ] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
  needed with deprecations, added features, breaking changes, and DB schema changes.
* [ ] I've decided if this PR requires a new major/minor version according to
  [semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the next
  release branch if it's not a patch change.
</details>

### What

Adds a check in the transaction submission workflow, where it returns the bad sequence error immediately if Horizon and Core sync up with each other.

### Why

During a particular edge-case, if core reports bad-seq error, and Horizon and Core are synced up with each other, the txsub endpoint will still timeout instead of returning the error immediately.

closes #5192 

This is a bug due to how Horizon will keep waiting for the account sequence to catch up to the submitted tx seq.

### Known limitations

NA

### CODE REVIEW

File: services/horizon/internal/txsub/system.go [hunk 1]
```diff
@@ -142,6 +144,14 @@ func (sys *System) Submit(
 			return
 		}
 
+		// Check if Horizon and Core have synced up: If yes, then no need to wait for account sequence
+		// and send txBAD_SEQ right away.
+		currentStatus := sys.LedgerState.CurrentStatus()
+		if currentStatus.CoreLatest == currentStatus.HistoryLatest {
+			sys.finish(ctx, hash, resultCh, Result{Err: sr.Err})
+			return
+		}
```
Comment (mollykarcher) [inline services/horizon/internal/txsub/system.go:153]: Defer to @Shaptic or @sreuland on if this is the best way to compare core/ingest states. But we need to move this logic _inside_ `waitUntilAccountSequence`. Will it as it is here, imagine this sequence of events:
- state: account is at sequence number 5 and horizon ingestion is lagging behind core
- a user submits a tx with sequence number 7
- we execute this check on line 150, and it continues on because horizon is lagging behind
- we enter `waitUntilAccountSequence`
- horizon ingestion catches up
- `waitUntilAccountSequence` continues to loop waiting for the account sequence number to go to 6, which will never happen

What we need is for `waitUntilAccountSequence` to exit/terminate when ingestion is caught up.

Comment (aditya1702) [reply services/horizon/internal/txsub/system.go:153]: @mollykarcher Yeah that makes sense. Did not think of this edge-case

Comment (sreuland) [reply services/horizon/internal/txsub/system.go:153]: yea, good point, repeating this same [status check](https://github.com/stellar/go/pull/5191/files#diff-5846d16bb162a4a6ca1e880ef01f59b654f19302c0ef9e90f3d7fab959ceb5b1R149-R153) from the polling iteration in `waitUntilAccountSequence` instead of here gives it a bit more resiliency, same timeliness of up front check as realized here on 1st iteration of polling, and additional opportunity to still exit early if the same condition happens on ensuing poll iterations any time up to the context time out.

Comment (Shaptic) [reply services/horizon/internal/txsub/system.go:153]: Yep, agreed with this.

And I _think_ this seems like a good way to check state (from the code, those statuses seem like they're updated on each app tick), but you could `<=` to be safer.

File: services/horizon/internal/txsub/system_test.go [hunk 2]
```diff
@@ -281,6 +315,64 @@ func (suite *SystemTestSuite) TestSubmit_BadSeqNotFound() {
...
+		suite.successXDR,
+		suite.successTx.Transaction.TransactionHash,
+	)
+
+	assert.NotNil(suite.T(), r.Err)
+	assert.True(suite.T(), suite.submitter.WasSubmittedTo)
+}
+
+// If error is bad_seq and horizon and core are in sync, then return error
+func (suite *SystemTestSuite) TestSubmit_BadSeqNotFoundWhenInSync() {
```
Comment (sreuland) [inline services/horizon/internal/txsub/system_test.go:345]: should this test case read `TestSubmit_BadSeqReturnedWhenInSync()` , maybe that can be demonstrated further with additional assert on `r.Err = BadSeq` after [line 387](https://github.com/stellar/go/pull/5191/files#diff-28500168bb477ec1663bf8c8c364b8f87c1886bdafd087f557c04a41af3bd398R387)?

**Review by sreuland — APPROVED** [review]
lgtm, nice work on pulling up the StateInterface to enable a unit test with mocking!

File: services/horizon/internal/txsub/system_test.go (hunk 2 above)
Comment (aditya1702) [reply services/horizon/internal/txsub/system_test.go:345]: Hmm, yeah that would work. Will change that.

**Review by Shaptic — APPROVED** [review]

File: services/horizon/internal/ledger/main.go [hunk 3]
```diff
@@ -1,15 +1,9 @@
-// Package ledger provides useful utilities concerning ledgers within stellar,
-// specifically as a central location to store a cached snapshot of the state of
-// both horizon's and stellar-core's views of the ledger.  This package is
-// intended to be at the lowest levels of horizon's dependency tree, please keep
-// it free of dependencies to other horizon packages.
```
[the remark this answers is not in the document]
Comment (aditya1702) [reply services/horizon/internal/ledger/main.go:5]: Oops did it by mistake. Good catch 😅
