### PR TITLE
services/friendbot: adds Stellar channels to friendbot

### LINKED ISSUE #1156: Friendbot slows down under heavy load along with increased `tx_bad_seq` errors
Screen Shot 2019-04-19 at 10 32 54 AM

you can see the stretch where I issued 11 in quick succession (req. num. 4 - req. num. 14), the response time slows down from 10.79s to 40s resulting in 3 failures caused by `tx_bad_seq`. When I re-issue requests it goes back to the 7-13s range until I start bombarding it agaon.

friendbot currently spawns new goroutines for every submission and also assumes that transactions will be submitted in the order in which they were created. These threads are probably taking a toll on the machine and also resulting in `tx_bad_seq` errors because of message ordering.
We are already `lock`ing before creating a new transaction so we only create one request at a time and issue only 1 seq number at a time. we submit using multiple goroutines so we’re not bottlenecked on ledger close times.

Screen Shot 2019-04-19 at 10 24 24 AM

`tx_bad_seq` has been friendbot’s biggest enemy (because of high throughput requirements). we’ve considered using channels in the past etc.

The `lock`ing logic explains the slowness when issuing multiple requests. Although I'd imagine it's not that expensive to just make a tx and submit asynchronously so the amount of slowness is unexplained.

possible solutions:
- [ ] we should consider making use of stellar channels so we can have different pools of seq numbers to consume. I think if we were to have 10 such stellar channels that would be plenty. they wouldn’t need more than 100 XLM at any given point in time. we can also have friendbot itself monitor it’s own channel accounts and fund it if any of them ever get low. If we don’t want to manage these channel accounts, we can always have friendbot create these throwaway accounts on startup so we don’t have to manage their keys.
- [ ] batch requests into 2s chunks so we submit multiple ops / tx (susceptible to DoS attacks by pre-creating an account submitting to friendbot after inclusion in the batch, so tx fails all ops)

startup command can add a `-n` or `--num-channels` flag which specifies the total number of channels to initialize friendbot with. We can linearly initialize each channel account in batches of 100 each synchronously to keep things simple. We could artificially limit max number of channels to 1000 using a constant value so startup time is within `1000/100 * 5 seconds = 50 seconds`. The faster way to initialize would be to first initialize with 100 channels and then use those hundred channels to then create more channels in a geometric fan-out model. We don't need that kind of scale with friendbot right now.

We would also need a background thread that monitors these source accounts. If any of them ever fall below a certain threshold, say 20 XLM, then this background thread can "top-up" these source accounts with a transaction that does not use a source account. This thread can run once per hour.

### PR DESCRIPTION
**Pull request by debnil**
This PR adds Stellar channels to friendbot. The goal is to reduce bad sequence errors (`tx_bad_seq`) and general slowness during heavy load. The new `Minion` struct contains the Stellar channel, a sequence number, and associated methods that are moved from `Bot`. `Bot` contains a list of `Minions`. This also updates friendbot to use the new Go SDK. Closes #1156, #1249  .

### CODE REVIEW

File: services/friendbot/init_friendbot.go [hunk 1]
```diff
@@ -13,24 +15,71 @@ func initFriendbot(
 	networkPassphrase string,
 	horizonURL string,
 	startingBalance string,
+	numMinions int,
```
Comment (nikhilsaraf) [inline services/friendbot/init_friendbot.go]: this can be a uint16, then we don't need the manual check below

File: services/friendbot/init_friendbot.go [hunk 2]
```diff
@@ -13,24 +15,71 @@ func initFriendbot(
...
+		AppName: "friendbot",
+	}
+
+	minions := make([]internal.Minion, numMinions)
+	for i := 0; i < numMinions; i++ {
+		minionSecret, err := createNewAccount(friendbotSecret, networkPassphrase, hclient)
+		if err != nil {
+			return nil
+		}
+		minions = append(minions, internal.Minion{
```
Comment (nikhilsaraf) [inline services/friendbot/init_friendbot.go]: I think this will create extra minions. instead of appending here we should assign the value at `minions[i]`. Alternatively, don't initialize `minion` with a fixed length if we append here.
example: https://play.golang.org/p/7bB3v_7poHY

File: services/friendbot/init_friendbot.go [hunk 3]
```diff
@@ -13,24 +15,71 @@ func initFriendbot(
...
+		URL:     horizonURL,
+		HTTP:    http.DefaultClient,
+		AppName: "friendbot",
+	}
+
+	minions := make([]internal.Minion, numMinions)
+	for i := 0; i < numMinions; i++ {
+		minionSecret, err := createNewAccount(friendbotSecret, networkPassphrase, hclient)
+		if err != nil {
+			return nil
```
Comment (nikhilsaraf) [inline services/friendbot/init_friendbot.go]: this should return a wrapped error, the return type for this method should be updated to return the bot and an error.

File: services/friendbot/init_friendbot.go [hunk 4]
```diff
@@ -13,24 +15,71 @@ func initFriendbot(
...
 		StartingBalance:   startingBalance,
 		SubmitTransaction: internal.AsyncSubmitTransaction,
+		Minions:           minions,
+	}
+}
+
+func createNewAccount(sourceSeed, networkPassphrase string, hclient *horizon.Client) (string, error) {
+	destKeypair, err := keypair.Random()
+	if err != nil {
+		return "", nil
```
Comment (nikhilsaraf) [inline services/friendbot/init_friendbot.go]: we should return a wrapped error instead of nil

File: services/friendbot/init_friendbot.go [hunk 5]
```diff
@@ -13,24 +15,71 @@ func initFriendbot(
...
+		Horizon:           hclient,
 		Network:           networkPassphrase,
 		StartingBalance:   startingBalance,
 		SubmitTransaction: internal.AsyncSubmitTransaction,
+		Minions:           minions,
+	}
+}
+
+func createNewAccount(sourceSeed, networkPassphrase string, hclient *horizon.Client) (string, error) {
+	destKeypair, err := keypair.Random()
```
Comment (nikhilsaraf) [inline services/friendbot/init_friendbot.go]: we should call this `keypair` or `kp` instead of `destKeypair`. the fact that this is a destination is a concept that is above this method, which only cares about creating new accounts.

File: services/friendbot/init_friendbot.go [hunk 6]
```diff
@@ -13,24 +15,71 @@ func initFriendbot(
...
+	if err != nil {
+		return "", nil
+	}
+	destAddr := destKeypair.Address()
+	tx, err := build.Transaction(
+		build.SourceAccount{AddressOrSeed: sourceSeed},
+		build.Network{Passphrase: networkPassphrase},
+		build.AutoSequence{SequenceProvider: hclient},
+		build.CreateAccount(
```
Comment (nikhilsaraf) [inline services/friendbot/init_friendbot.go]: this should be a batched operation that creates up to 100 stellar channel accounts per transaction. That's the only way we can achieve scale in creating many channel accounts.

this create account method can be changes to `createAccounts` which takes in an `N` value and returns a list of string which is the secret keys

if N is above 100 then it would create multiple transactions to push these through. Alternatively you can have one method that creates max of 100 accounts in a single transaction and the outer loop controls how many times this can be called.

this should specify a starting balance that is taken in as a param in the function.

Lastly, can we not reuse the existing friendbot method to create accounts instead of creating this new method? especially since friendbot only creates accounts :)

File: services/friendbot/internal/friendbot.go [hunk 7]
```diff
@@ -2,151 +2,158 @@ package internal
...
+	nextMinionIndex   int
 }
 
-// Pay funds the account at `destAddress`
+// Pay funds the account at `destAddress`.
+// XXX: Change return type
 func (bot *Bot) Pay(destAddress string) (*horizon.TransactionSuccess, error) {
-	channel := make(chan TxResult)
-	err := bot.lockedPay(channel, destAddress)
+	minion := bot.Minions[bot.nextMinionIndex]
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot.go]: where is this called from -- don't we need to pass it on to the minion in a new thread?
we'll also need to lock when we select a minion and unlock after we submit the account info into the minion's channel

File: services/friendbot/internal/friendbot.go [hunk 8]
```diff
@@ -2,151 +2,158 @@ package internal
...
-	}
-
-	signed, err := bot.makeTx(destAddress)
+	signed, err := minion.makeTx(destAddress, bot.Secret, bot.Network, bot.StartingBalance)
 	if err != nil {
-		return err
+		return nil, err
 	}
+	go bot.SubmitTransaction(&minion, bot.Horizon, signed)
+	bot.nextMinionIndex = (bot.nextMinionIndex + 1) % len(bot.Minions)
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot.go]: nice! 👍

File: services/friendbot/internal/friendbot.go [hunk 9]
```diff
@@ -2,151 +2,158 @@ package internal
...
+func (minion *Minion) makeTx(destAddress, botSecret, networkPassphrase, initBalance string) (string, error) {
 	txn, err := b.Transaction(
-		b.SourceAccount{AddressOrSeed: bot.Secret},
-		b.Sequence{Sequence: bot.sequence + 1},
-		b.Network{Passphrase: bot.Network},
+		b.SourceAccount{AddressOrSeed: minion.Secret},
+		b.Sequence{Sequence: minion.sequence + 1},
+		b.Network{Passphrase: networkPassphrase},
 		b.CreateAccount(
 			b.Destination{AddressOrSeed: destAddress},
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot.go]: these can be combined into one operation.

File: services/friendbot/internal/friendbot.go [hunk 10]
```diff
@@ -2,151 +2,158 @@ package internal
...
+			b.NativeAmount{Amount: initBalance},
 		),
 	)
 
 	if err != nil {
 		return "", errors.Wrap(err, "Error building a transaction")
 	}
 
-	txs, err := txn.Sign(bot.Secret)
+	txs, err := txn.Sign(botSecret, minion.Secret)
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot.go]: nice!

File: services/friendbot/internal/friendbot.go [hunk 11]
```diff
@@ -2,151 +2,158 @@ package internal
...
-	bot.lock.Lock()
-	defer bot.lock.Unlock()
-
-	err := bot.checkSequenceRefresh()
-	if err != nil {
-		return err
-	}
-
-	signed, err := bot.makeTx(destAddress)
+	signed, err := minion.makeTx(destAddress, bot.Secret, bot.Network, bot.StartingBalance)
```
Comment (nikhilsaraf) [inline services/friendbot/internal/friendbot.go]: we should somehow reuse these makeTx and submitTransaction methods when creating the minion channels

Comment (debnil) [reply services/friendbot/internal/friendbot.go]: I thought about this, but I'm not sure how. The route to reuse seems to be placing these two methods on the bot. But then we can't launch them on the minion's thread. Any thoughts?

Comment (nikhilsaraf) [reply services/friendbot/internal/friendbot.go]: since the minion channel creation logic will be doing a bulk transaction for up to 100 minions per tx we don't need to reuse this for now.

File: services/friendbot/internal/friendbot.go [hunk 12]
```diff
@@ -1,152 +1,29 @@
...
 }
 
-func (bot *Bot) address() string {
-	kp := keypair.MustParse(bot.Secret)
-	return kp.Address()
+// Pay funds the account at `destAddress`.
+func (bot *Bot) Pay(destAddress string) (*hProtocol.TransactionSuccess, error) {
+	minion := bot.Minions[bot.nextMinionIndex]
+	resultChan := make(chan SubmitResult)
+	go minion.Run(destAddress, resultChan)
```
[the remark this answers is not in the document]
Comment (debnil) [reply services/friendbot/internal/friendbot.go]: Ah, got it - I was getting deadlock in my implementation of the long-running goroutines, but I'm happy to give that another stab in future.

File: services/friendbot/internal/account.go [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+import (
+	"strconv"
+
+	"github.com/stellar/go/clients/horizonclient"
+	"github.com/stellar/go/support/errors"
+	"github.com/stellar/go/xdr"
+)
+
+// Account implements the `txnbuild.Account` interface.
+type Account struct {
```
[the remark this answers is not in the document]
Comment (debnil) [reply services/friendbot/internal/account.go]: This actually inspired #1271 , which will be in the next Go SDK release. I can replace `internal.Account` with `txnbuild.SimpleAccount` then!

File: services/friendbot/internal/friendbot.go [hunk 14]
```diff
@@ -1,152 +1,29 @@
...
+	bot.nextMinionIndex = (bot.nextMinionIndex + 1) % len(bot.Minions)
+	maybeSubmitResult := <-resultChan
+	close(resultChan)
```
[the remark this answers is not in the document]
Comment (debnil) [reply services/friendbot/internal/friendbot.go]: Maybe I'm misunderstanding - but this function also creates `resultChan`, isn't this the proper usage?

[the remark this answers is not in the document]
Comment (nikhilsaraf) [reply services/friendbot/internal/friendbot.go]: my understanding is that the _sender_ should close the channel. the receiver has the option to check if a channel is closed and respond accordingly. 
This is a good reference I've used in the past when thinking about closing go channels: https://go101.org/article/channel-closing.html

File: services/friendbot/internal/account.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (nikhilsaraf) [reply services/friendbot/internal/account.go]: ok sounds good, thanks for the context!
